<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Exp. TOS Hours_Main</name>
   <tag></tag>
   <elementGuidId>32afadb2-142b-4aba-8719-e0f26e0113e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exp_tosHrsid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exp_tosHrsid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#exp_tosHrsid</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4f70a82-4408-4c3b-99e6-d3548f2d75eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7289dec5-7579-4e1d-9104-66e0811e4e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exp_tosHrsid</value>
      <webElementGuid>2fb92e14-871d-4d3d-8672-8ff086d6f3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>224da710-1882-4b82-a288-fadd6c25cd20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>793725ad-29f1-4636-bfe0-0e0efbf32aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Exp_tosHrs</value>
      <webElementGuid>cf6fe3e4-38db-4493-b9ca-6d2aa45916d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk</value>
      <webElementGuid>f9744a0a-dfb5-414d-963e-75d7dd26aaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exp_tosHrsid&quot;)</value>
      <webElementGuid>f455fbc5-8666-4b1c-bbe3-7dc5ea61c328</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exp_tosHrsid']</value>
      <webElementGuid>78dca5d8-d085-4cfb-b7a1-f74a66d21c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/span[4]/input)[13]</value>
      <webElementGuid>c919635f-e7d3-4c5d-acd1-8111eece17b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[6]/li/div/span[4]/input</value>
      <webElementGuid>9aeb7236-4885-4bbd-baf2-4a27e8b3b1cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'exp_tosHrsid' and @name = 'chk']</value>
      <webElementGuid>1e8905ee-3eb6-4902-98d3-81a74c39e663</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
