<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Custom Metrics_Main</name>
   <tag></tag>
   <elementGuidId>25807115-2b22-4c6a-8460-8a6d1ac42464</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustMet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CustMet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#CustMet</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97cdba57-5979-48ab-a5d1-8f7eaf408d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3ff83771-ab56-4e27-857e-e81fce6b76f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>76f3e17e-5544-4b73-994d-012537f50ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustMet</value>
      <webElementGuid>3c8378dd-52ad-4e2e-bca2-01aaba7779bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>CustMet</value>
      <webElementGuid>0c77c9d4-df6d-42fb-9e3b-6fc856e5f42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CustMet</value>
      <webElementGuid>8e80216a-5b1a-4974-b849-63909b937675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_CustMet AVG_CustMet</value>
      <webElementGuid>ebb982ef-d1e7-4dd4-908c-3184b0b1f307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustMet&quot;)</value>
      <webElementGuid>e93f1f0c-5615-4eda-9823-72862f676650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustMet']</value>
      <webElementGuid>b0bc762d-1f4d-4da4-9301-2460a3472279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[7]</value>
      <webElementGuid>cc1221e0-3cbb-4dc2-a275-12295ba53d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[7]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>96645e59-13e8-49fe-909a-b0ef22426019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'CustMet']</value>
      <webElementGuid>e2db04ba-d57d-47e4-b936-474794508e6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
