<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Custom Metrics_Avg</name>
   <tag></tag>
   <elementGuidId>86328407-0182-47c1-bdf2-8e796ebf26e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AVG_CustMet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AVG_CustMet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AVG_CustMet</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48588121-aaa2-41d8-a761-800150ad327c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4eb721b1-af58-47d9-9117-bfc7be9de227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AVG_CustMet</value>
      <webElementGuid>a3575f0c-a1b4-411b-9482-1336c7e41562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>0ad46584-883d-45ae-9382-f8d84e295f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnToggleMetricsOnClick</value>
      <webElementGuid>f3d126d9-d088-439e-bb25-ab1c0c6772ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Avg</value>
      <webElementGuid>03ac5046-a35f-44f5-aa02-fdc67d656d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk activityChk> vertical-align-top</value>
      <webElementGuid>f33e6ebb-0cb3-4455-b387-de9e04268763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-classname</name>
      <type>Main</type>
      <value>CustMet</value>
      <webElementGuid>86526be8-2154-4653-8885-670e08bda0cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AVG_CustMet&quot;)</value>
      <webElementGuid>8e2c821c-65a7-4c3b-b700-e7ce40718d95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AVG_CustMet']</value>
      <webElementGuid>65771003-46e9-4a40-9c13-fed95ec8e612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr[3]/td/span/input[2])[3]</value>
      <webElementGuid>b587ff5f-9f5f-4ecb-b258-73ec31538bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[7]/li/div/table/tbody/tr[3]/td/span/input[2]</value>
      <webElementGuid>597f2d97-d958-4b9c-819f-e114f0eff293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'AVG_CustMet' and @name = 'chk']</value>
      <webElementGuid>3a72806f-b739-409a-b41a-23cbdbd03865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
