<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Day Types_Main</name>
   <tag></tag>
   <elementGuidId>2b3507d5-37e8-4452-8cdd-505b6c024e39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dayTypesColumnChk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dayTypesColumnChk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dayTypesColumnChk</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6602455-c6a7-4f32-8723-490c80328d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>84670d5c-34c1-4088-8a34-72e9e8118a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>feb1327a-da14-4a72-9d6a-f1e21368ad77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>7c1597fe-1c05-4302-9798-bbcac69bd433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dayTypesColumnChk</value>
      <webElementGuid>24a50597-04fb-41ff-876f-798d57008579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>DAY_TYPE_COUNT</value>
      <webElementGuid>0a9764c7-fcd2-49ca-8ade-7f4d672e553e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DAY_TYPE_COUNT</value>
      <webElementGuid>924b0f14-586b-4f71-bd9b-6f0baa5abaf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk</value>
      <webElementGuid>b4636090-bd5f-4e6b-8081-954fb11e47b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dayTypesColumnChk&quot;)</value>
      <webElementGuid>879224eb-c356-4353-8b67-473c77cf5548</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dayTypesColumnChk']</value>
      <webElementGuid>9b38fa6d-a060-440f-b3b7-433c362ce6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/span[3]/input)[9]</value>
      <webElementGuid>fb186d57-5e76-4a82-b127-703b09061a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[4]/li/div/span[3]/input</value>
      <webElementGuid>ccdec3c4-1ee2-4237-886b-42f7f0ada451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chk' and @id = 'dayTypesColumnChk']</value>
      <webElementGuid>bbd2f123-e742-41e0-819a-33cd22774382</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
