<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Work Output_CustWO</name>
   <tag></tag>
   <elementGuidId>c0786216-7b51-4ff5-8af4-eee32cc4a902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustWO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CustWO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#CustWO</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5fb20bb-84d1-4edc-b8fd-0b2fd9f27d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a3cc0d3d-fe06-4f74-a452-1079aa1062cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>f48fe8ca-d6bc-4e02-9b36-8663830d6a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustWO</value>
      <webElementGuid>4e209780-bec4-4b42-b15a-9af013551510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>CustWO</value>
      <webElementGuid>e4fe81a9-60b0-4ee8-9d9b-ce8099825160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CustWO</value>
      <webElementGuid>4e5671c3-6293-4e40-965e-6e3a6b3bb1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CustWO CustWO</value>
      <webElementGuid>c6764366-0770-4d30-9b9e-166b0766472a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustWO&quot;)</value>
      <webElementGuid>03a89481-106f-46da-9ef1-91e16935f7ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustWO']</value>
      <webElementGuid>c0c87ee2-fa21-4a3c-9a0c-1cf23484382e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[4]</value>
      <webElementGuid>57141396-83d7-492d-bd03-3f3379ff18f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[6]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>4a257f2b-0df1-4f52-916b-f27fb30843e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'CustWO']</value>
      <webElementGuid>f2f67d3f-f889-4072-a31f-698f6d7229a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
