<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Specific Activities_Tot</name>
   <tag></tag>
   <elementGuidId>d0a53f0e-3577-495a-8660-1cef0cc21033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TOT_CustAct</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TOT_CustAct']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TOT_CustAct</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7da62d9-530b-4dfe-9a92-9256a0cb29f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>435ba058-2a81-428c-93b0-625fa6ee2a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TOT_CustAct</value>
      <webElementGuid>7333db68-2af2-44eb-bde6-d0d99b3d4c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>85c98f78-b9cd-471a-a1c5-48f85656eb54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnToggleActivityOnClick</value>
      <webElementGuid>2d06c88e-5b68-4bda-b972-b7733dc64d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tot</value>
      <webElementGuid>a1a1ffed-67ff-4faa-9092-8138782d7c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk activityChk vertical-align-top</value>
      <webElementGuid>6503fd82-6c7b-40cc-a754-1b322c3794ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-classname</name>
      <type>Main</type>
      <value>CustAct</value>
      <webElementGuid>350d786d-e463-4db3-a8be-3f34bbea683a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TOT_CustAct&quot;)</value>
      <webElementGuid>7924d756-0270-4bc1-b9d8-8887e93bace0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TOT_CustAct']</value>
      <webElementGuid>5e3ebfa5-311e-45c9-9786-ba129ad9d2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='current']/table/tbody/tr[3]/td/span/input</value>
      <webElementGuid>cf985487-f89f-4112-ba24-cd6aa29b3e48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/table/tbody/tr[3]/td/span/input</value>
      <webElementGuid>5d0042ca-ec04-45d0-b1d8-4c667d0d9d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'TOT_CustAct' and @name = 'chk']</value>
      <webElementGuid>31d0f8de-5c72-4fa6-ae1a-4a1a808cafba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
