<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Specific Activities_Main</name>
   <tag></tag>
   <elementGuidId>e3264a39-28cd-4ade-ae86-08650df72528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustAct</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CustAct']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#CustAct</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5139092a-35dc-4f2b-b64c-0a68df98191d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>30c4a085-ff32-4ffb-8a02-db8ea9b6bb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>53a7b019-1df2-415a-8c7e-58664de33af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustAct</value>
      <webElementGuid>e54910be-309f-4e74-96ec-9bdefaf956c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>CustAct</value>
      <webElementGuid>8fcfbe96-25ae-4d01-8fae-79aee00974fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>CustAct</value>
      <webElementGuid>0dcb24f6-0e70-422d-b11c-17d475896efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_CustAct AVG_CustAct</value>
      <webElementGuid>e930e568-c5c6-4c5a-8224-cad431cfaaef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustAct&quot;)</value>
      <webElementGuid>41d9c7f3-3758-482a-ae19-82dfa62c8886</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustAct']</value>
      <webElementGuid>0000ce68-b3db-4839-b92d-be906c0f7a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='current']/table/tbody/tr/td/span/input</value>
      <webElementGuid>58106d94-fe7f-47c0-b273-772a6167fae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>396c8d02-6443-45e5-9fab-5d32ca2096e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'CustAct']</value>
      <webElementGuid>0488d8e6-1d0b-4028-90be-da9d93ef7dee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
