<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Specific Activities_Avg</name>
   <tag></tag>
   <elementGuidId>c7858a04-12d0-4f76-936c-7c376adc592b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AVG_CustAct</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AVG_CustAct']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AVG_CustAct</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a8e150f3-2075-4578-903d-0d1cb0a23c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c0f15e78-ce27-4e8e-ac65-a79a4e91f29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AVG_CustAct</value>
      <webElementGuid>4aecc2b6-c6a0-4364-be14-bdce1670bcca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>d3e9e696-ed8d-43d6-8159-947dda689e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnToggleActivityOnClick</value>
      <webElementGuid>6096a495-b08a-44e4-b1ee-b83bedaadd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Avg</value>
      <webElementGuid>5695db42-fc5b-4ee9-9323-bc642d25bf25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk activityChk> vertical-align-top</value>
      <webElementGuid>2a2ab0fc-e2d0-425e-9a5b-e8f0b00b3b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-classname</name>
      <type>Main</type>
      <value>CustAct</value>
      <webElementGuid>ad2e014f-96e8-484d-b04d-8457b8f5e763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AVG_CustAct&quot;)</value>
      <webElementGuid>1609a36f-e378-4ab9-9efb-6eb48f713450</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AVG_CustAct']</value>
      <webElementGuid>8fadb777-91cf-491d-bab9-492c58e55169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='current']/table/tbody/tr[3]/td/span/input[2]</value>
      <webElementGuid>55f9e330-c90b-42e4-8b3c-6a84e43d22e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/input[2]</value>
      <webElementGuid>59fd7721-aa06-412d-bd88-90b206ad6bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'AVG_CustAct' and @name = 'chk']</value>
      <webElementGuid>5249134e-ece1-4dad-a50e-e36f91fe18b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
