<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Top Applications For All Groups_drilld_ef368b</name>
   <tag></tag>
   <elementGuidId>59ac0dd7-3d4a-4234-971f-d36bf370ae14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='drilldown-container_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#drilldown-container_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#drilldown-container_3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e63c734b-f473-4407-9527-d4d40330cbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>6d34c7a6-c286-47c4-9e8f-51ec38de413f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drilldown-container_3</value>
      <webElementGuid>8b57a728-4fe0-4d53-8110-f00406ac7e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>widget-tools tool-detail drilldown-container_3 showDrillDown</value>
      <webElementGuid>39e96beb-6658-459b-939f-9788805125a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-divid</name>
      <type>Main</type>
      <value>container_3</value>
      <webElementGuid>6486c439-9e06-447e-85d9-9c44d7fa6c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param1</name>
      <type>Main</type>
      <value>NTopAppsDetailsReport</value>
      <webElementGuid>41a81bda-5b22-4272-b43d-498adcfa3b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param2</name>
      <type>Main</type>
      <value>G_TOP_APP_GROUP_REP</value>
      <webElementGuid>2621c346-5ff7-46bb-8df1-eae87a92926d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param3</name>
      <type>Main</type>
      <value>container_3</value>
      <webElementGuid>881275f5-5b5f-47ae-84ed-2c7709c2d7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param4</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8cb73533-d57f-4c79-bb0b-a34773f5716e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param5</name>
      <type>Main</type>
      <value>39</value>
      <webElementGuid>a535f388-a42b-4298-bf52-609e120b049d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drilldown-container_3&quot;)</value>
      <webElementGuid>2b475d56-1029-4f90-b847-c5dfac9b2bbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='drilldown-container_3']</value>
      <webElementGuid>e3fe74bf-e20a-46ea-8d1c-e33a16dc26eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widgetId_container_3']/div/div[2]/span[2]</value>
      <webElementGuid>c3366d38-f62e-441d-aa19-077e6d4f91e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div[2]/span[2]</value>
      <webElementGuid>1632e294-afe6-4612-84d1-3ee1a3c7a2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'View Details' and @id = 'drilldown-container_3']</value>
      <webElementGuid>2892c135-8c56-4b9b-93d7-c1ffd5d42db6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
