<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>general2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>cf3880ea-0e14-41cd-b864-d20a2456ebbc</testSuiteGuid>
   <testCaseLink>
      <guid>56ab1144-4ee1-4916-8440-ee52fae061cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProhanceWeb/General_TC/General_TC</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>83007726-69cc-4e6e-83ff-f5225d609fbe</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>2-2</value>
         </iterationEntity>
         <testDataId>Data Files/LoginPage/LoginPage</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>83007726-69cc-4e6e-83ff-f5225d609fbe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>6072c373-d0aa-41c1-97f0-1f3a79b7deae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>83007726-69cc-4e6e-83ff-f5225d609fbe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>b97b1ae6-9a00-494b-8cd0-c6e6d35c742f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>83007726-69cc-4e6e-83ff-f5225d609fbe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>exportType</value>
         <variableId>6faa5939-a322-4ea0-86b7-c0676a8376cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c37aeab-71bd-41a4-97ea-38e5e33312bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f57e042-9675-43d6-a78f-f2b9c660a054</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>571362ed-f065-4f5f-bd99-70e6823726d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c6ec449-e377-410d-9eda-21f2c57b8dab</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
