<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login_Genaral</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>dd30f850-7cc8-45fa-90d6-36303e149b49</testSuiteGuid>
   <testCaseLink>
      <guid>58aac47b-3425-4042-bd56-9c9ea66eb7cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProhanceWeb/Login_Page/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>236a136c-d6f6-42a8-ae54-b2124d273f0a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginPage/LoginPage</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>236a136c-d6f6-42a8-ae54-b2124d273f0a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>abb36807-d3bd-4b16-af3a-45d3d2e11cac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>236a136c-d6f6-42a8-ae54-b2124d273f0a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>dfad082c-e840-418a-a98c-292c3ae56617</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b4f9513-e30a-4100-adf8-4ddcfe153e06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProhanceWeb/Organization Settings/Work Time/Activity DashBoard/ActivityDashBoard</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dabaadb1-5810-4404-a014-66dca6824e15</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Activity Dashboard/Group Widgets/Top Application</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>dabaadb1-5810-4404-a014-66dca6824e15</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>exportType</value>
         <variableId>d41db5d9-148b-4fd0-a782-e364b051317f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dabaadb1-5810-4404-a014-66dca6824e15</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>isFileDownload</value>
         <variableId>1a8d04e1-88b9-438f-9639-b085f577f841</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dabaadb1-5810-4404-a014-66dca6824e15</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>isDataValion</value>
         <variableId>d2fe38e6-3540-471d-9b42-5308c5d4d0c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>042c0460-eed5-410d-9792-4565bebca5e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e240312b-4d95-491e-bbfc-3b687f54be30</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f19b7162-7d2f-429a-ad18-611c70c509c4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProhanceWeb/LogOut_Page/LogOut</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
