<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login_Genaral</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>dd30f850-7cc8-45fa-90d6-36303e149b49</testSuiteGuid>
   <testCaseLink>
      <guid>58aac47b-3425-4042-bd56-9c9ea66eb7cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProhanceWeb/Login_Page/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>236a136c-d6f6-42a8-ae54-b2124d273f0a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/LoginPage/LoginPage</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>236a136c-d6f6-42a8-ae54-b2124d273f0a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userName</value>
         <variableId>abb36807-d3bd-4b16-af3a-45d3d2e11cac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>236a136c-d6f6-42a8-ae54-b2124d273f0a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>dfad082c-e840-418a-a98c-292c3ae56617</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b4f9513-e30a-4100-adf8-4ddcfe153e06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProhanceWeb/Organization Settings/Activity DashBoard/ActivityDashBoard</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
