<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Active_Hours_Main</name>
   <tag></tag>
   <elementGuidId>95748ce6-f391-436a-a434-2cb2903d89e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#THrs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='THrs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#THrs</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecb39496-0a84-456d-b61c-b39af5650158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>957c6e56-ec67-4a8f-8e9f-6d71d6d99da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>fc777e67-734a-40d8-a40e-a136eae0fc20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>THrs</value>
      <webElementGuid>d9214337-67d7-481a-97ba-17f41bf29133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>THrs</value>
      <webElementGuid>bea520a9-1a8c-4c2b-8766-fc8baaf38ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>THrs</value>
      <webElementGuid>04b6a602-1139-40d4-9ef5-133160547b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_THrs AVG_THrs</value>
      <webElementGuid>c5a02a6f-fde5-4fda-9090-238a457c22ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;THrs&quot;)</value>
      <webElementGuid>a559ae48-96a9-45d0-b46c-53d57f9729b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='THrs']</value>
      <webElementGuid>aad01f7a-b717-4a43-a478-42e08111cb7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[6]</value>
      <webElementGuid>47a6e908-98b0-4d1e-ae8d-650f93d7e77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>b6aaad9a-b478-40fc-a245-407d87831aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'THrs']</value>
      <webElementGuid>2a454393-cc29-4bd8-8bcc-25331ceabecb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
