<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Logged_Hours_Main</name>
   <tag></tag>
   <elementGuidId>7d4dc33b-54a3-402f-93ca-0631fc08869d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LHrs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LHrs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#LHrs</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3354f22e-5d26-47fb-b579-bf00020accb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>07a44d3f-4184-4ad7-8211-c32740fa72a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>3c5d251e-5c51-47f1-ba95-b77b4f4fd5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LHrs</value>
      <webElementGuid>1657c615-0061-4fc4-8d90-c68a41d925a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>LHrs</value>
      <webElementGuid>037a1947-f4de-42cf-b876-f9871dcfdf19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LHrs</value>
      <webElementGuid>8ff4d443-cf4b-461e-9887-ffe289b02bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_LHrs AVG_LHrs</value>
      <webElementGuid>db6b26c6-3a94-495e-8b10-110c58076ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LHrs&quot;)</value>
      <webElementGuid>14d621fc-1e74-493a-b030-8a19269462a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LHrs']</value>
      <webElementGuid>9ab3e4e5-1a4d-4f39-a8ab-1f6de1e63c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='current']/table/tbody/tr/td/span/input</value>
      <webElementGuid>26ca33f2-e7d7-4259-8cba-e8966c66d976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>9f3e649e-48a8-4fe7-9a47-39d740e48d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'LHrs']</value>
      <webElementGuid>78b8309b-11f3-4dde-8bfc-be281af08799</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
