<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Neutral (TOS)_Main</name>
   <tag></tag>
   <elementGuidId>b39b80bc-7939-4c4e-8ad5-16296a39b0ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TOS_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TOS_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TOS_2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd576432-f36e-4641-9034-913aeae315bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ed4a8659-f884-4992-a02b-1ab69ae3934f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>587dcf5c-6646-4676-b16b-ccf6811363ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TOS_2</value>
      <webElementGuid>e62bdb00-bc87-4def-994e-4752412f76ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TOS_2</value>
      <webElementGuid>c741a332-b7cc-4c30-b6a3-59ecd50e0ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>TOS_2</value>
      <webElementGuid>aad6da63-1d38-4c94-9f51-eb6ee1537f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_TOS_2 AVG_TOS_2</value>
      <webElementGuid>f7feccdd-3242-47a0-a797-4f125b0ee9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TOS_2&quot;)</value>
      <webElementGuid>eeffeac1-6597-416f-a6eb-9df58a4c501b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TOS_2']</value>
      <webElementGuid>c8e6336d-f44b-4914-bd2e-3c5c1cc3a229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[21]</value>
      <webElementGuid>00968ccd-300f-45e5-a012-7547502a44d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>ffd2b400-6766-4e95-8e9d-cd760257b8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'TOS_2']</value>
      <webElementGuid>c09b3785-3c75-4681-a86b-c8b1f02b9bff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
