<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Non Productive (TOS)_Main</name>
   <tag></tag>
   <elementGuidId>c9cc8fd2-e885-411f-92f0-5e5f4341313e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TOS_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TOS_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TOS_3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0842ed12-2073-4144-a7a1-459943d5de24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>40590466-c0d7-49e6-b78d-b59b070ff167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>458743da-e1b7-4607-93fc-1b25167914fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TOS_3</value>
      <webElementGuid>86af1b3a-2594-41a5-b791-007f82728be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TOS_3</value>
      <webElementGuid>349aea56-9d6f-4a4f-b744-5aaa921dc2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>TOS_3</value>
      <webElementGuid>23d63ac9-d6a7-4e29-89c6-aaea189229d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_TOS_3 AVG_TOS_3</value>
      <webElementGuid>7d79e498-c35c-4dd7-98b8-98b1cccf6a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TOS_3&quot;)</value>
      <webElementGuid>0d6477dd-5fc0-46b9-827d-72fe9689e3a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TOS_3']</value>
      <webElementGuid>3ad7c9d5-8e92-42f2-8d06-4b7daed3de17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[16]</value>
      <webElementGuid>e554a6ca-7fbe-44ae-b9bf-b719d22c0edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[3]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>d68e512f-3fb7-4ffd-a3e2-f8d10cc1e3cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'TOS_3']</value>
      <webElementGuid>7d58f979-ab16-4c1b-9f89-ed4c0aa244d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
