<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Not Rated (TOS)_Main</name>
   <tag></tag>
   <elementGuidId>0022320f-1399-48e8-b73a-0f32fd65f2df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TOS_N_R</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TOS_N_R']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TOS_N_R</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd7c3179-0b04-47e9-a3a8-f76e2903acdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>06861c97-8908-4c6f-8a92-6d2df6139651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>ef209996-77a7-44b0-acc7-53ce1e6aec2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TOS_N_R</value>
      <webElementGuid>e6a47262-b53c-496b-9695-321f70d39fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TOS_N_R</value>
      <webElementGuid>269c1367-1937-442d-b89f-75dd17b24656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>TOS_N_R</value>
      <webElementGuid>2dd1d899-4232-4e2a-8729-346c4491ceec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_TOS_N_R AVG_TOS_N_R</value>
      <webElementGuid>97888f32-be3c-4b69-ae46-0922dda9df95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TOS_N_R&quot;)</value>
      <webElementGuid>1838f66c-c979-45d5-be44-faab3a881151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TOS_N_R']</value>
      <webElementGuid>80a2bd65-257b-42ac-bcae-f3b5ef9b12e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[31]</value>
      <webElementGuid>503579fe-3fc6-41e3-a7c5-972a7174f842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[4]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>fd3dab9e-be2f-46ae-b3b3-26316d15a880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'TOS_N_R']</value>
      <webElementGuid>4dced4c4-3888-4005-a3ce-9630a9b6adfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
