<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Personal Time (TOS)_Main</name>
   <tag></tag>
   <elementGuidId>3ec4884f-03ef-4a5a-9778-69fb6b76ff9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Personal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Personal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Personal</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b036a25-6752-465d-956d-677fcad81816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9b19d1fa-b8a7-4284-95ed-b666bdcae1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>3fbda6d3-dd02-45c5-90dc-83e4077afaea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Personal</value>
      <webElementGuid>ab05bbef-a045-4b1f-b465-f5bbad5b8978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Personal</value>
      <webElementGuid>177a15ab-5275-496d-bef2-df0a58dc9c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>Personal</value>
      <webElementGuid>b4a4e870-4b96-49ac-8de8-38b4c880432e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_Personal AVG_Personal</value>
      <webElementGuid>594c0104-3872-4a52-bfae-3c51c4522b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Personal&quot;)</value>
      <webElementGuid>8b7f2838-87c6-4ae8-bc0a-e508a98037a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Personal']</value>
      <webElementGuid>1a500c71-10d1-4fb9-9847-6f21ca394f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[41]</value>
      <webElementGuid>ef9b7b75-535c-4acf-9088-3315b43dab31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/ul[6]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>fe70e3c0-3bb1-4b0f-9e1c-961324956c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'Personal']</value>
      <webElementGuid>760a3182-0a5f-49ab-886b-8277e46ef78d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
