<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Productive (TOS)_Tot</name>
   <tag></tag>
   <elementGuidId>ab44019c-0377-499b-a879-b447f4240bd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TOT_TOS_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TOT_TOS_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TOT_TOS_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28c82861-b4d4-4ad4-8dec-2aec97bcd4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3666947d-83a7-47fd-b8c6-a9532b516623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>22f679ab-fecc-42d5-b45b-2f8da7040fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TOT_TOS_1</value>
      <webElementGuid>12e80ba3-bfa9-4d98-b992-65efb80726b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>4092422c-37cc-4e8d-9080-15df7dc6b1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TOT_TOS_1</value>
      <webElementGuid>dfd2716c-5145-4ac2-9266-e3812b23de41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-classname</name>
      <type>Main</type>
      <value>TOS_1</value>
      <webElementGuid>5517cf81-dfa3-432c-89f0-d6b5da53213b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk TOS_1 vertical-align-top</value>
      <webElementGuid>f71b48cb-d9b9-4735-8fa2-12ccf0acc7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TOT_TOS_1&quot;)</value>
      <webElementGuid>e9b00f29-f20f-4e41-addc-9896e2bb3c72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TOT_TOS_1']</value>
      <webElementGuid>e6a72016-e96f-4a02-9477-bc1e1137af87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr[3]/td/span/input)[13]</value>
      <webElementGuid>57d6a25e-ec46-4e11-b659-fc54ad7fd8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/ul/li/div/table/tbody/tr[3]/td/span/input</value>
      <webElementGuid>ba75047f-ebdb-46ce-a0c5-5d3583192ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chk' and @id = 'TOT_TOS_1']</value>
      <webElementGuid>04a9b9b4-5072-4fed-ab82-b8ebad72a6ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
