<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Productive (TOS)_Main</name>
   <tag></tag>
   <elementGuidId>7c7fc8f6-bb7c-482b-b940-8e3dde5622f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TOS_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TOS_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TOS_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28034c1b-3285-4fb8-83ee-c1aac3af0994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>961bf2d7-92cf-4c74-8d77-e6aa9d1df390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>353caaf4-2465-476b-bb44-53477c1f88cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TOS_1</value>
      <webElementGuid>9650a37c-0639-4725-9b84-c46dd3222afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TOS_1</value>
      <webElementGuid>f8919452-a635-4576-b29f-b9d947e2e560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>TOS_1</value>
      <webElementGuid>7911b401-d660-418a-afc2-73e99721972b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_TOS_1 AVG_TOS_1</value>
      <webElementGuid>45dd7a3b-c588-4c0b-9029-b6534c92d0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TOS_1&quot;)</value>
      <webElementGuid>f9b0d168-1351-4b9a-9366-4ae0e9ddb373</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TOS_1']</value>
      <webElementGuid>21236dca-a3f0-4602-9a78-9873ac4e53c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[16]</value>
      <webElementGuid>78ecc542-88a5-4217-bd86-b29ff805dfba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/ul/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>9ed385f7-4529-4bc3-bf62-0b78238d6d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'TOS_1']</value>
      <webElementGuid>0f099ce4-180a-4aba-84f5-d343f8470a5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
