<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Time On System_Main</name>
   <tag></tag>
   <elementGuidId>32268c6d-36b5-4170-8b78-89caad15c212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Tos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Tos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Tos</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e315555d-f74b-4f14-a75b-efd5f6b35feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4e6c5ddb-4dc8-4b94-8eb4-538eab3c5675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>97617bee-22ba-4c88-b133-07ad1b23143c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Tos</value>
      <webElementGuid>1133b3c0-87cd-4636-a80f-4a047065aba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tos</value>
      <webElementGuid>044ff02f-f4cd-4acd-9e13-9e9fd590aa3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>Tos</value>
      <webElementGuid>5f303b40-5553-4b58-b423-0c23a737b936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_Tos AVG_Tos</value>
      <webElementGuid>ea91f6ba-b575-4bc4-8bd3-ff9b4ac56091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Tos&quot;)</value>
      <webElementGuid>a3eeef7c-3a56-4f6f-865a-b779e35ea9dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Tos']</value>
      <webElementGuid>cc0f37e9-ebcb-4bd2-a7b2-29e304a0dbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[11]</value>
      <webElementGuid>779a0e81-4f68-49b8-b7a9-501c16ab4d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>70a663a9-f624-452c-93c3-982cae6cda70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'Tos']</value>
      <webElementGuid>4aed4165-edd6-4468-9b9b-189c4e7e195a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
