<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Time On System_Tot</name>
   <tag></tag>
   <elementGuidId>76e95f51-f9d3-44f7-9231-ed9ef6389784</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TOT_Tos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TOT_Tos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TOT_Tos</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5108eb6-b60e-4ccd-a1cb-e0dd789de98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>90b2954e-fa6e-423a-b370-0756e79576fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>abfd7890-75af-4a67-b0e5-fbf5c2e01fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TOT_Tos</value>
      <webElementGuid>82a31cf2-7d76-45d7-8073-451df448478a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>1bffae3e-e5ef-4220-869b-9e23004a8d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TOT_Tos</value>
      <webElementGuid>9df596f6-b985-4d6c-9f4f-0446188fb162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-classname</name>
      <type>Main</type>
      <value>Tos</value>
      <webElementGuid>a9487e78-06ae-4904-9d5a-492fa1a7554f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk Tos vertical-align-top</value>
      <webElementGuid>41c2cff9-708e-416e-9b41-c9f0417d20ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TOT_Tos&quot;)</value>
      <webElementGuid>6d9631c0-c06d-40c6-a5ee-0fac33b69414</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TOT_Tos']</value>
      <webElementGuid>be147707-a4c5-4789-a7bc-7c49034ae3ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr[3]/td/span/input)[9]</value>
      <webElementGuid>bac9e875-e961-4eaf-a04e-bd4218f2881c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/div/table/tbody/tr[3]/td/span/input</value>
      <webElementGuid>fdf11d2d-1c88-434d-ac2a-d31a4d401420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chk' and @id = 'TOT_Tos']</value>
      <webElementGuid>d7db6e27-ef09-4af0-a844-9559ec1dc3c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
