<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unknown (TOS)_Avg</name>
   <tag></tag>
   <elementGuidId>048bf6f4-a308-4ca5-a54c-8fd2458abd00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AVG_UApp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AVG_UApp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AVG_UApp</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fdcb8786-96ff-4c90-8d79-5f49e5a02899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fb24ac49-9656-42e0-a40e-61316bb99e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>c792ad6d-e8bc-46e4-9323-33a39fa7704c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AVG_UApp</value>
      <webElementGuid>0c9b1382-ee34-4761-bb21-acd65bb00fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>1749b06b-4c64-4e7a-b8c4-120c66d6a66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AVG_UApp</value>
      <webElementGuid>4ce9e1da-4eb5-46f4-aeb2-718e63f180b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-classname</name>
      <type>Main</type>
      <value>UApp</value>
      <webElementGuid>e798013c-3a61-4c5a-8777-f4a0d3028135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk UApp vertical-align-top</value>
      <webElementGuid>ea1ffb29-4932-4190-b4e8-a40682b27454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AVG_UApp&quot;)</value>
      <webElementGuid>37e2e222-dc75-4b18-a7d0-45479a7fa153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AVG_UApp']</value>
      <webElementGuid>d0bbb365-3e0c-4217-a3d7-bad6029432aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr[3]/td/span/input[3])[8]</value>
      <webElementGuid>0e391eb9-80a2-4dae-a0cc-5db3587dd923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[5]/li/div/table/tbody/tr[3]/td/span/input[3]</value>
      <webElementGuid>65d86874-9722-4d3f-9409-6c43e93218d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chk' and @id = 'AVG_UApp']</value>
      <webElementGuid>a4e00a4d-f475-4627-aa8e-83f904d30d1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
