<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unknown (TOS)_Tot</name>
   <tag></tag>
   <elementGuidId>b92746db-c34f-4bd2-9945-96b7f7022d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TOT_UApp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TOT_UApp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TOT_UApp</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b6588e6-b4e2-44ff-8e01-3c787fe751d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cdaed174-8a0d-4c1f-81f1-4c530cf7276b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>85abbc8f-f6de-4588-b3e1-7512091bb411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TOT_UApp</value>
      <webElementGuid>d561ef9d-8af9-4c7e-93dd-810da1c43681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>a07aad40-3453-4a00-a878-ba584e4c2b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TOT_UApp</value>
      <webElementGuid>9dd3b4ce-1b6f-42a2-aa2c-e5c43c20e622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-classname</name>
      <type>Main</type>
      <value>UApp</value>
      <webElementGuid>ceba39bf-1600-47ab-b4b8-296c4a31c2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk UApp vertical-align-top</value>
      <webElementGuid>ebb611b8-76c0-4c2a-ac24-e7335dbb8d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TOT_UApp&quot;)</value>
      <webElementGuid>074e3fe1-af58-44ac-b01c-591b0a30492f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TOT_UApp']</value>
      <webElementGuid>156f6c78-fe80-4c94-b106-e953889b53ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr[3]/td/span/input)[29]</value>
      <webElementGuid>69fd6eab-9d17-447b-9195-62ae354ecb43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/ul[5]/li/div/table/tbody/tr[3]/td/span/input</value>
      <webElementGuid>1428855a-13d6-46de-afbd-aa1d249a3ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chk' and @id = 'TOT_UApp']</value>
      <webElementGuid>3ebb9599-d373-4c55-8542-12b0de9c649a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
