<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unknown (TOS)_Main</name>
   <tag></tag>
   <elementGuidId>e89ca7c0-4b99-42c2-811a-a74dfad112d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UApp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UApp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#UApp</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ebcdd3d-f686-4110-bf3a-4b67ad98250a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f0e89912-94e9-4fd7-a87b-87aa6a305845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>bd2fb5c7-1ff9-4c07-a60e-a9626528d513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UApp</value>
      <webElementGuid>92369cb2-e7f9-4914-b377-1afc825c29c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>UApp</value>
      <webElementGuid>2a78bca8-9a29-4d1b-bec5-63ca6ea1ae7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>UApp</value>
      <webElementGuid>d9f3bbc9-88e8-4c02-80b6-6241f8ad89ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_UApp AVG_UApp</value>
      <webElementGuid>7e6427a0-dca7-43eb-bb04-2a40feddc771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UApp&quot;)</value>
      <webElementGuid>a4c2e4ea-45b4-4819-8424-a8d46d56d143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UApp']</value>
      <webElementGuid>9ff753d2-ac5b-4645-93b2-8edc93292e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[36]</value>
      <webElementGuid>8d2b500a-da61-4dfe-8c13-a15468aecc3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li/ul[5]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>fee47221-24a0-4003-a74f-70e63c04375c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'UApp']</value>
      <webElementGuid>60ba38cd-6ddc-4d90-b822-d154b4719010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
