<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>configuration</name>
   <tag></tag>
   <elementGuidId>360695d0-132b-43a2-bf92-8cd0ee3675f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='OrganizationSettingsFormId']/table/tbody/tr/td[2]/div[5]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;#100 Do not display the details in reports  &amp; configuration &quot;i] >> label >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3de03a15-ebdc-479c-a8c2-8e948bcdf21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>hasUnknownAosConfig</value>
      <webElementGuid>e802b8af-be1a-43c8-965a-01b2e5598399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OrganizationSettingsFormId&quot;)/table[@class=&quot;configtable&quot;]/tbody[1]/tr[1]/td[@class=&quot;tabletdodd&quot;]/div[@class=&quot;nolabelcheckbox nolabelcheckbox-success padding-Left-10px&quot;]/label[1]</value>
      <webElementGuid>afa0c322-d02a-4381-b8e0-ebbcc1b2008a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='OrganizationSettingsFormId']/table/tbody/tr/td[2]/div[5]/label</value>
      <webElementGuid>15cf5186-fe39-416c-9331-7dd7ff90c6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label</value>
      <webElementGuid>ff594791-fa59-4b74-9ef8-172d7f9c2021</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
