<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Displaynon-configuredAOS</name>
   <tag></tag>
   <elementGuidId>a5b29c2b-b661-4e78-81f3-d9227b4fbb3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unconfiguredApplicationLabel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#unconfiguredApplicationLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#unconfiguredApplicationLabel</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb8f658b-7514-4c95-80ac-75e3d4199c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unconfiguredApplicationLabel</value>
      <webElementGuid>ea1cbfb6-d9e6-40ba-9767-26f06037dc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unconfiguredApplicationLabel</value>
      <webElementGuid>6df6622e-2546-4bb2-b9a3-8c111b26b25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox width-35percentage</value>
      <webElementGuid>1a50e90a-6708-41d6-aea5-5eaee8ecdd26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d263c60-8af8-4d36-b865-1515d866f24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>UNKNOWN AOS</value>
      <webElementGuid>f71a0614-f75e-4f13-9707-cfe0ffb47567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>589f5973-26db-4717-b3e9-7350d1e5a29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unconfiguredApplicationLabel&quot;)</value>
      <webElementGuid>afc7b643-9292-459a-bcc7-860644b8c451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Organization Settings/iframe_Hierarchy Mapping_contentFrame</value>
      <webElementGuid>c7d4436b-36b6-49e7-86be-777cdba55aa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unconfiguredApplicationLabel']</value>
      <webElementGuid>6dd226eb-0dd5-4ef8-bc1b-9deb8304de81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='OrganizationSettingsFormId']/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>ae4b1d1b-337d-4953-8d40-d406551c51ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>dd5ce9d2-ac5c-4155-8a4d-ea1e016adf28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'unconfiguredApplicationLabel' and @name = 'unconfiguredApplicationLabel' and @type = 'text']</value>
      <webElementGuid>514a7341-57c9-4053-8b2b-2dd3c413c261</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
