<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Donotdisplaythedetailsinreports</name>
   <tag></tag>
   <elementGuidId>9757b8be-f42d-4d59-8ed0-bb4c857b3fa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='OrganizationSettingsFormId']/table/tbody/tr/td[2]/div[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;#100 Do not display the details in reports  &amp; configuration&quot;i] >> label >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>80c8ca66-b020-43aa-98a7-940c5d3a2fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>hasUnknownAosDrilldown</value>
      <webElementGuid>93feb4a4-1f92-413f-90bf-ee157732aa29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OrganizationSettingsFormId&quot;)/table[@class=&quot;configtable&quot;]/tbody[1]/tr[1]/td[@class=&quot;tabletdodd&quot;]/div[@class=&quot;nolabelcheckbox nolabelcheckbox-success padding-Left-10px&quot;]/label[1]</value>
      <webElementGuid>b0522050-417c-409a-b5c2-f867d01ed670</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='OrganizationSettingsFormId']/table/tbody/tr/td[2]/div[3]/label</value>
      <webElementGuid>b104811f-459f-4c68-b25c-b02b6a35ccd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>25b138e0-2323-4da6-8d67-4850a6699f7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
