<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>unconfiguredAafsReference</name>
   <tag></tag>
   <elementGuidId>369a36f2-b710-4bab-be8b-cd48d8734d5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unconfiguredAafsReference']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#unconfiguredAafsReference</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#unconfiguredAafsReference</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31e44b64-f941-4d97-9978-af71cef81dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unconfiguredAafsReference</value>
      <webElementGuid>d6dd99b8-cb21-4daf-afc4-111454bfbd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unconfiguredAafsReference</value>
      <webElementGuid>42fe210e-e3a0-4ac6-83cd-959822ab034f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>6390c054-fe11-4c6a-85f8-4d8bcdd3c3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>833de0bf-e735-40f8-9f13-293a5afde727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>UNKNOWN</value>
      <webElementGuid>4adb7bd2-4a01-47f0-b8de-75d7328810ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>99c9101a-5ec3-4a12-bb21-4caf32452a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unconfiguredAafsReference&quot;)</value>
      <webElementGuid>c38fbaec-b837-4c9a-9a97-ee8bb642f7a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unconfiguredAafsReference']</value>
      <webElementGuid>5c9dc4c0-4604-40e7-833c-8d8304fc4e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='OrganizationSettingsFormId']/table/tbody/tr[2]/td[2]/div/input</value>
      <webElementGuid>4459d982-9c5a-47d1-80bd-af0bda2cfdaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/input</value>
      <webElementGuid>9df685be-91a0-4830-bae4-cf67d431dbac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'unconfiguredAafsReference' and @name = 'unconfiguredAafsReference' and @type = 'text']</value>
      <webElementGuid>a2a89069-8002-4100-b732-aaf52bf3fbe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
