<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>friDay_Chk</name>
   <tag></tag>
   <elementGuidId>a92bf198-fecb-482a-b19b-696de2084636</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='weekCheckFri']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#weekCheckFri</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Friday&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d1c8464-523f-462b-9c2d-2a3ab1c29298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>caba5a0b-ef3a-49e3-8b24-288498ff8067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>actionSel modal_dayofweek</value>
      <webElementGuid>9d3fa597-b9a8-4d25-946a-e24e3e3b5979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>weekCheckFri</value>
      <webElementGuid>303325ec-ef4c-40f4-a8b0-787c29404955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>3496759f-b7e3-4e80-9046-eb0f88a4079d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnCheckSelectAllDayOfWeekOnClick</value>
      <webElementGuid>15db2a61-d8d1-485a-bd1e-15527e6a6011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param1</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>08174a46-8f26-4e79-9918-f227be87b427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param2</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7ff15e59-c275-4710-8c73-311c0333043e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weekCheckFri&quot;)</value>
      <webElementGuid>a00438e0-e81d-4da5-a2c5-35ac75b81af3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='weekCheckFri']</value>
      <webElementGuid>56b2fde7-e32d-4a0e-9540-94492708b26e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dayOfWeekTable']/tbody/tr/td/table/tbody/tr[6]/td/div/input</value>
      <webElementGuid>85d9a1c5-2c2a-4fd8-910f-4e3ebc8fcd39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td/table/tbody/tr[6]/td/div/input</value>
      <webElementGuid>b5a04104-9311-49ab-bada-2ae81bfa6a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'weekCheckFri']</value>
      <webElementGuid>dbae746c-2502-43f3-b672-801507059782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
