<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select All_Chk</name>
   <tag></tag>
   <elementGuidId>f9af38bc-4f17-45d2-90b3-0cb8002e863e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectAllDayOfWeekNameId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectAllDayOfWeekNameId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=checkbox[name=&quot;Select All &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60292f70-a47f-4d63-aa6d-6899f98eabe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1f25d907-6936-4eb1-9e4a-a822628fa90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled</value>
      <webElementGuid>955818a6-a45c-49a6-9997-e0907121ea55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectAllDayOfWeekNameId</value>
      <webElementGuid>34240be6-8a44-4584-a668-9c2784885b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selectAllDayType</value>
      <webElementGuid>d4754f0a-0b46-48a8-bf9b-d571678ff089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnSelectAllDayOfWeekOnClick</value>
      <webElementGuid>e973659c-14c1-4d3a-8e39-5880fbe4bd9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectAllDayOfWeekNameId&quot;)</value>
      <webElementGuid>5e6bde59-2af1-4016-8194-f2eaa252f2a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectAllDayOfWeekNameId']</value>
      <webElementGuid>3f3cec8e-b18b-4251-8211-32a052c371a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dayOfWeekTable']/tbody/tr/td/table/tbody/tr/th/div/input</value>
      <webElementGuid>2c82c6ce-bed7-49cd-94c4-0282903c1df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td/table/tbody/tr/th/div/input</value>
      <webElementGuid>6dd6a242-5273-40e0-8921-e19515e66ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'selectAllDayOfWeekNameId' and @name = 'selectAllDayType']</value>
      <webElementGuid>e3aa7075-62c5-4a88-9da1-b881f6b7c0c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
