<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sunDay_Chk</name>
   <tag></tag>
   <elementGuidId>ca7077e1-ea7d-4150-9669-4b1c455632bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='weekCheckSun']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#weekCheckSun</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sunday&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a97b7454-e716-4941-898b-82617ebe97db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7d2b4c07-656c-4c66-bffd-d88ce44a7804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>actionSel modal_dayofweek</value>
      <webElementGuid>5ce38e8e-15c6-4f3c-8348-5f27724bc264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>weekCheckSun</value>
      <webElementGuid>38fc068c-62c1-4953-b087-778a27e0f118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>239cd94f-1470-4508-ad62-034f04b96b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnCheckSelectAllDayOfWeekOnClick</value>
      <webElementGuid>43c9f0b3-5486-4410-94e7-d0882b9a7db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param1</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>df98971d-7016-46d7-b980-8b8bd4984ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param2</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9de41c72-1832-4893-94e5-0b09bd1f8356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weekCheckSun&quot;)</value>
      <webElementGuid>c084b516-1685-470d-83b1-76879210dcc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='weekCheckSun']</value>
      <webElementGuid>8cfd9607-40b8-4d19-aeb8-d611e80f3dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dayOfWeekTable']/tbody/tr/td/table/tbody/tr[8]/td/div/input</value>
      <webElementGuid>725ae962-14ca-4a0d-aa86-b43b339f92f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/div/input</value>
      <webElementGuid>1cde13bf-f56e-45de-9489-bea18bbd63a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'weekCheckSun']</value>
      <webElementGuid>347a1833-b9f8-4dde-9ee1-9d52f91fdbc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
