<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Exp. TAFS Hours_Main</name>
   <tag></tag>
   <elementGuidId>1d28870b-f88f-49db-901d-6294e53572fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exp_tafsHrsid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exp_tafsHrsid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#exp_tafsHrsid</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91a18748-f3d9-440f-a452-71cbff646092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>47c2e00c-acaa-4962-bf05-615269c2ee4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exp_tafsHrsid</value>
      <webElementGuid>82fb0a47-4096-4e36-9c93-41bb6560d8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>05bf3260-51cf-48c4-8141-0f8c6941af51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>6faeb12a-4878-486f-9116-222d714d3cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Exp_tafsHrs</value>
      <webElementGuid>65d04679-286b-485c-9a26-be7c6cb75e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk</value>
      <webElementGuid>749171bb-0f69-47a8-bad4-6754573d065f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exp_tafsHrsid&quot;)</value>
      <webElementGuid>254d1b3d-06be-4b03-a96e-e72dd97b0896</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exp_tafsHrsid']</value>
      <webElementGuid>16434e44-bb6e-43a5-8dc6-1463f063a89f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/span[4]/input)[15]</value>
      <webElementGuid>76763880-cc8f-4ef0-a577-0dc6c571af15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul[7]/li/div/span[4]/input</value>
      <webElementGuid>d89e89a9-48ac-4e98-8836-73e59306db95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'exp_tafsHrsid' and @name = 'chk']</value>
      <webElementGuid>f091587f-39fc-4a01-9dad-cac45943aca4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
