<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FETCH</name>
   <tag></tag>
   <elementGuidId>d21ac412-5a4d-48d5-aede-8601c7eca04c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.goButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dropdown-menu-id']/table/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;FETCH&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>acba5fcc-e36c-4efd-aff8-eafb1d053a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>goButton</value>
      <webElementGuid>cb9eb586-c63f-48c0-b94a-020e7cad03cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							FETCH
							</value>
      <webElementGuid>ef0315f7-52b8-4b83-b2e2-4baf1c8be477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdown-menu-id&quot;)/table[@class=&quot;reportDurationTable&quot;]/tbody[1]/tr[1]/td[@class=&quot;goButton&quot;]</value>
      <webElementGuid>f4bab277-f0cd-46ed-bbd2-2dd5bd6b5745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dropdown-menu-id']/table/tbody/tr/td[3]</value>
      <webElementGuid>399ec4fa-4d80-4747-a33e-98bd86c24f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Today'])[1]/following::td[2]</value>
      <webElementGuid>de411f6b-3bf0-4ee1-a312-3f1c75b444e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Week'])[1]/following::td[2]</value>
      <webElementGuid>f23f96e5-97fa-48ac-892c-1e0733e6d298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Standard'])[2]/preceding::td[1]</value>
      <webElementGuid>67a2c696-dcbf-48d2-ad0c-2187701617fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>e5b83fd6-56de-41b9-8481-ce3b467e63fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
							FETCH
							' or . = '
							FETCH
							')]</value>
      <webElementGuid>ca64c55a-0eaa-45df-9768-758d18e5caaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
