<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Display Overall Data_showByGroup</name>
   <tag></tag>
   <elementGuidId>dfd1c24d-3afb-46fb-80ca-a4202edb0732</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showByGroup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='showByGroup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Display data&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c349bafc-bb3e-413b-b496-5631836d028e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c41080b7-5805-46aa-b374-b8f8e7643415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>showByGroup</value>
      <webElementGuid>e483f38c-3332-4312-b030-f807789fce3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showByGroup</value>
      <webElementGuid>7de331b0-2506-4c9f-b268-4df09c3f2a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4711fa7c-407c-4c50-936a-731e6e188e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnCheckShowByGrpOnClick</value>
      <webElementGuid>f42d659e-fc0c-45b6-a846-9fdf04191be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showByGroup&quot;)</value>
      <webElementGuid>7a1c6338-f8d4-4f39-ba97-f61c3a715559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='showByGroup']</value>
      <webElementGuid>eba6b9db-99ca-412d-9a78-a43c7fe8a3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='showByGroupSpan']/div/input</value>
      <webElementGuid>5992ccfb-8c8d-47d4-863f-aa98a3c4e6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/input</value>
      <webElementGuid>e070d04b-e440-442f-af6a-a7f083583ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'showByGroup' and @id = 'showByGroup']</value>
      <webElementGuid>b68d3459-97f1-4edb-ae88-ceb172eceb2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
