<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ingnore_Consider</name>
   <tag></tag>
   <elementGuidId>09a5d701-42cb-46e6-bd6a-997d4514d8d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showByGroup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input [@ id='id='lhValue1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Display data&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6123f6e0-a064-4412-92d7-51da797d6194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c36e8cd7-2885-480a-9d9c-1ef883d945e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>showByGroup</value>
      <webElementGuid>bca64754-cb62-4ef8-9334-8b92d645afb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showByGroup</value>
      <webElementGuid>7157143b-4c7a-4627-b820-79e9374f77ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>17deb7c4-376f-4cfe-961f-54f2474d1eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnCheckShowByGrpOnClick</value>
      <webElementGuid>5cad375f-cbba-4b45-97b6-5eaef1cf1243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showByGroup&quot;)</value>
      <webElementGuid>7f8abad5-a0a7-4195-b795-5852b6c22fdc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
