<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_View By_displayOverallData</name>
   <tag></tag>
   <elementGuidId>52cf70b3-ee19-40e5-bdce-242071b3637d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#displayOverallData</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='displayOverallData']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Display Overall Data&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d44130d2-d70a-4ac9-afa1-e5dba045f2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b134e61f-8177-4707-a144-c1a733bd1890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>displayOverallData</value>
      <webElementGuid>fd97bc21-0995-478b-9794-187455343c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>displayOverallData</value>
      <webElementGuid>1ea923cf-3512-4b1b-af66-8c13765a9a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9fb51648-e826-4075-b63b-611931370189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;displayOverallData&quot;)</value>
      <webElementGuid>9e06fc05-b12a-4e8c-bd91-e324f0f6dc6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='displayOverallData']</value>
      <webElementGuid>42454c01-b20e-4745-8579-2583c4f84577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buttonDiv']/div/span/div/input</value>
      <webElementGuid>1400224c-934e-4b1c-abd4-43bf54149602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/input</value>
      <webElementGuid>ff855375-c3d6-428e-a36d-2adcde5de27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'displayOverallData' and @id = 'displayOverallData']</value>
      <webElementGuid>64a5f5a1-a84f-4748-ab6f-f3795879e5f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
