<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Less then_Greate then</name>
   <tag></tag>
   <elementGuidId>544f393b-e997-460a-85f3-f8cdd8c82188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dayFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select [@ id='lhCondition']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dayFilter</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1d40a824-467f-474b-9034-d4c58b2bbfec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>width-150px form-control form-control-filter</value>
      <webElementGuid>7cce463d-bfaf-4a0b-8218-5e10014f69e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dayFilter</value>
      <webElementGuid>998ee895-49c8-45a8-b3d7-ec92546de3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dayFilter</value>
      <webElementGuid>d49a7ba2-7d47-45fd-b856-8226188c1e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onchange</name>
      <type>Main</type>
      <value>fnPopulateDropDownfnCheckDaysOnChange</value>
      <webElementGuid>b455f27e-b688-48cf-bf45-14c7f4f8bd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param1</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bed796e8-2f9b-4a30-93be-abdf40f7e438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					Day Type
			        Day of Week
			</value>
      <webElementGuid>01577a20-80d8-40db-a1c5-040250f9e57d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dayFilter&quot;)</value>
      <webElementGuid>9eec0ebb-936a-4155-9574-a723723a420a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
