<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Report By_Main</name>
   <tag></tag>
   <elementGuidId>19dd28eb-b79d-44f8-8f77-37f90411f3ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customReportViewByFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='customReportViewByFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#customReportViewByFilter</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>98ee9d19-9952-43ad-9f38-c031e0e57efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>width-150px form-control form-control-filter</value>
      <webElementGuid>34b4ce78-98db-4ebb-bd6e-c3f8f37efab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reportViewBy</value>
      <webElementGuid>4bc96928-6907-4f2b-bbf1-02d79ed6444d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customReportViewByFilter</value>
      <webElementGuid>3ae6818f-f157-41bc-aae6-49983b0f20fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onchange</name>
      <type>Main</type>
      <value>fnChangeReportFilterOnChange</value>
      <webElementGuid>a5f275a0-0f89-4678-8c70-aaf51ee844ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User GroupsUserUser RoleDesignationSkill SetLocationServicelineBandSpecializationRegionStateTenure Range</value>
      <webElementGuid>e5161b4a-63ae-498a-97c7-a9f1a7136103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customReportViewByFilter&quot;)</value>
      <webElementGuid>cb2fb884-6f21-4b2b-b1ca-e456a6a515f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='customReportViewByFilter']</value>
      <webElementGuid>8c2d031d-b51c-4d91-b41d-3b7d6fbae950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='customizeReportByView']/select</value>
      <webElementGuid>c7c0bed6-b516-4c6b-b334-39327b4d0944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select All'])[1]/preceding::select[1]</value>
      <webElementGuid>8d88b8ab-13fb-4834-bf8e-f4bdbc3da0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Groups'])[5]/preceding::select[1]</value>
      <webElementGuid>c4eb7283-efab-4277-98e7-a3a03bb4dfea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/select</value>
      <webElementGuid>831e7610-c3b4-4adb-b2a8-14ffddb4892a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'reportViewBy' and @id = 'customReportViewByFilter' and (text() = 'User GroupsUserUser RoleDesignationSkill SetLocationServicelineBandSpecializationRegionStateTenure Range' or . = 'User GroupsUserUser RoleDesignationSkill SetLocationServicelineBandSpecializationRegionStateTenure Range')]</value>
      <webElementGuid>85feb86c-0ce0-423f-89a6-8bc2416b02f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
