<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Ingnore_Consider</name>
   <tag></tag>
   <elementGuidId>50364af7-0c47-426c-8b1d-75110e48ef9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dayFilter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select [@ id='lhType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dayFilter</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b8327e8c-4422-482b-bea1-96e9d728db08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>width-150px form-control form-control-filter</value>
      <webElementGuid>d5916f44-7456-40df-aa84-598afca761eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dayFilter</value>
      <webElementGuid>6723dd9a-74c1-4b9f-bc19-a0b3bc4924cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dayFilter</value>
      <webElementGuid>e9ee8eee-53d4-4426-b04e-34003cb0624b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onchange</name>
      <type>Main</type>
      <value>fnPopulateDropDownfnCheckDaysOnChange</value>
      <webElementGuid>b7c22ec8-dcb3-47e0-83c0-67fe959aaeed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param1</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0db05efb-b5f6-45de-8a2d-07e1b82c6f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					Day Type
			        Day of Week
			</value>
      <webElementGuid>3d00fb56-9b8f-45f3-b4d4-f1a99d7d5d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dayFilter&quot;)</value>
      <webElementGuid>d4d6ff51-77df-4017-9a30-39b97f214e38</webElementGuid>
   </webElementProperties>
</WebElementEntity>
