<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_View by_Main</name>
   <tag></tag>
   <elementGuidId>0b7d303b-29f6-4aee-9298-de80035bfcb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CustomDurationViewBy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CustomDurationViewBy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#CustomDurationViewBy</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5153d31a-ad7a-49eb-856f-b67657ccf2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-filter width-145px</value>
      <webElementGuid>231d7593-f97e-4fd7-926a-6afcb88e65f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>durationViewBy</value>
      <webElementGuid>8a586d88-9dbc-4ab9-b5c2-cac36b1317f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomDurationViewBy</value>
      <webElementGuid>a772b7e8-5afd-4821-8674-47a0981032f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onchange</name>
      <type>Main</type>
      <value>fnChangeViewFilterOnChange</value>
      <webElementGuid>fe06808b-e5bc-4540-bc19-62315ad4b54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Day</value>
      <webElementGuid>4d5b087b-2a80-42df-990c-e7592abdcc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustomDurationViewBy&quot;)</value>
      <webElementGuid>d140cec2-69a8-419e-85eb-e74b3f7654af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CustomDurationViewBy']</value>
      <webElementGuid>3ed67810-21e2-468a-89ab-cd69ceb48a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='customizeViewBy']/select</value>
      <webElementGuid>6f6e75a1-f9dc-4e56-839f-8b748651c5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Unit'])[4]/following::select[1]</value>
      <webElementGuid>a586ea08-9ac5-49ae-8c4c-8232a04d0546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/select</value>
      <webElementGuid>4f3ce12f-815c-41df-bd43-f24fec0ed2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'durationViewBy' and @id = 'CustomDurationViewBy' and (text() = 'Day' or . = 'Day')]</value>
      <webElementGuid>681a989a-555d-48ce-af6b-2ecd30b9208c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
