<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UPDATE FIELDS</name>
   <tag></tag>
   <elementGuidId>22be6b4f-7f79-4178-85e9-65a570b1d32e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#generateBut > #show-content-menu-main</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='show-content-menu-main'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;UPDATE FIELDS&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e94b9f3c-7bdb-4158-b522-a42b4da101c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-new-name</value>
      <webElementGuid>b339dba1-94bf-4243-a4d5-4e6b328c6b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>show-content-menu-main</value>
      <webElementGuid>543a74f8-fc8a-47bf-abb1-530323f3eb3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>data-show-content-menu-main</value>
      <webElementGuid>73a11edf-479a-422a-96e6-78a52ec80ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-functionname</name>
      <type>Main</type>
      <value>fnSubmitFilter</value>
      <webElementGuid>96c37b47-ea74-43e7-a9b9-10e43088e62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UPDATE FIELDS</value>
      <webElementGuid>fd3b6eb4-729c-41f4-b1fb-17da75922deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generateBut&quot;)/span[@id=&quot;show-content-menu-main&quot;]</value>
      <webElementGuid>fbe029a1-c557-4a71-99e2-b0364575f7ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='show-content-menu-main'])[2]</value>
      <webElementGuid>9d1b12bb-0fc9-43ef-a3fb-4650f43b02b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='generateBut']/span</value>
      <webElementGuid>63c0278a-0688-4814-946a-efba6eba1dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REPORT BY EMAIL'])[1]/following::span[5]</value>
      <webElementGuid>29c9af97-f1fc-49fb-8fef-5529ceab0920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BACK'])[1]/preceding::span[1]</value>
      <webElementGuid>278bc92d-4124-428e-8fe0-007ef9cb8dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customize Saved Views'])[1]/preceding::span[3]</value>
      <webElementGuid>723ce5a7-12b0-44ab-be5c-744186283e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='UPDATE FIELDS']/parent::*</value>
      <webElementGuid>1a4dd630-e3c5-4350-85a5-47f87aa70f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span</value>
      <webElementGuid>567415b0-cac0-463d-949b-591e568eb52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'show-content-menu-main' and (text() = 'UPDATE FIELDS' or . = 'UPDATE FIELDS')]</value>
      <webElementGuid>4830e547-a987-4143-816f-4bd95ecd7cd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
