<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Early Logout Duration _Tot</name>
   <tag></tag>
   <elementGuidId>cd6a00a9-733f-4a8f-8a76-58de3b0c22f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TOT_ELDuration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TOT_ELDuration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TOT_ELDuration</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>398ebb59-c87c-4319-947f-4e124e6fc494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ebb41fa4-3564-4c9b-a25c-ae1ef12102ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>ad41c764-19ce-41c8-8a5a-424d6a396c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TOT_ELDuration</value>
      <webElementGuid>9fdf1448-9dcf-4ffc-8e36-68e512235e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>a4b8b2e2-38a9-4751-a42c-f9edcdd983ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TOT_ELDuration</value>
      <webElementGuid>5201576e-0ca8-42fb-b643-c7597e94000a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-classname</name>
      <type>Main</type>
      <value>ELDuration</value>
      <webElementGuid>b91ceac8-021b-4c36-b5df-02f9aafda7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk ELDuration vertical-align-top</value>
      <webElementGuid>84b49f16-057a-4b8d-b470-78d327e6d660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TOT_ELDuration&quot;)</value>
      <webElementGuid>46be5b67-1162-4597-9fa1-8e717caa8e34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TOT_ELDuration']</value>
      <webElementGuid>ad848a9b-11cd-496e-94bc-6333219686a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr[3]/td/span/input)[9]</value>
      <webElementGuid>5c16790e-c7c2-4163-923c-d764f8b8611b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[9]/li/div/table/tbody/tr[3]/td/span/input</value>
      <webElementGuid>77f12aea-f098-49fa-8996-90ea45c57414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chk' and @id = 'TOT_ELDuration']</value>
      <webElementGuid>bbf998e2-a163-4281-8d7c-4ab89106027a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
