<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Early Logouts_Main</name>
   <tag></tag>
   <elementGuidId>6795ee12-69d2-45cf-b20b-e899efd0b6e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul:nth-of-type(8) > li > #current > span.text-align-left-float-left-padding-left-5px > input[name=&quot;chk&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input [@ class='efficiencychk' and @ value='ELCount' ]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#treeTd div >> internal:has-text=&quot;# Early Logouts&quot;i >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2ef48ca-b505-430a-a68c-eb9c2128f92a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4a8bd7a7-c031-4830-ac8c-e1c5efdb449c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>6cf80f60-3be2-4ccb-86e2-72d5f6410ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>cba61a2a-4b6a-4bb3-860e-416b77d3a1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ELCount</value>
      <webElementGuid>6c9a3032-17b7-458e-91c0-89d6c8acc8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk</value>
      <webElementGuid>336283e0-9bcf-4c03-a42d-99694dd62697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treeTd&quot;)/ul[@class=&quot;tree&quot;]/li[@class=&quot;border-top-1pxsolidc0c0c0-padding-top-10px&quot;]/ul[1]/li[2]/ul[1]/li[1]/ul[8]/li[1]/div[@id=&quot;current&quot;]/span[@class=&quot;text-align-left-float-left-padding-left-5px&quot;]/input[@class=&quot;efficiencychk&quot;]</value>
      <webElementGuid>7bc1eb48-9ceb-422d-a840-e2b4a306e74b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='chk'])[23]</value>
      <webElementGuid>705dd784-34dc-45ec-832e-a80d8c7d701f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/span[5]/input)[15]</value>
      <webElementGuid>676a1a26-eae1-43db-ab0b-a119d405d207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[8]/li/div/span[5]/input</value>
      <webElementGuid>5226c29a-8357-403f-a485-9ad2b46af4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chk']</value>
      <webElementGuid>0e1b6ba2-d4fb-444d-bdc1-bb510d7f7c39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
