<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Last Logout_User</name>
   <tag></tag>
   <elementGuidId>88d7232f-cd38-4453-90b1-32f2479d9d94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Last_Logout_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Last_Logout_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Last_Logout_id</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82d71a4d-343e-4113-ae4a-217a73157186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>282f3395-c924-44b3-b0f9-ff304719e5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Last_Logout_id</value>
      <webElementGuid>fceda5d0-ed39-4be1-b9ec-b3f3273ae29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>69c05072-3752-4eff-9876-876be0a3db74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>3d14211f-c19d-42e7-bb11-16f3271ba438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LLog</value>
      <webElementGuid>d8af85a8-8d04-4403-9b25-ff0914a222ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk</value>
      <webElementGuid>2ff61338-67e9-445e-8738-4a696186b9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Last_Logout_id&quot;)</value>
      <webElementGuid>2d1bab1c-d903-4002-9c85-90e38294c770</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Last_Logout_id']</value>
      <webElementGuid>ef403727-ae04-4779-9c8d-0c6a77448236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/span[5]/input)[3]</value>
      <webElementGuid>e4dc53bc-708e-40c7-a6fc-76a32e43fca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/ul/li/div/span[5]/input</value>
      <webElementGuid>889a770f-7d47-456b-a49f-65ec1bf5b557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'Last_Logout_id' and @name = 'chk']</value>
      <webElementGuid>d3788aee-0cfc-467f-b4c7-07150246f5f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
