<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Late Login Duration_Main</name>
   <tag></tag>
   <elementGuidId>75e73a61-873d-463b-9b7d-911576e5e499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LLDuration</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LLDuration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#LLDuration</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2298365c-f374-4178-9934-dc79eddef09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d0c868ad-511a-4639-b6c7-5b6b55b608ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>b75320d6-218a-4fde-9e46-e1868a2ced9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LLDuration</value>
      <webElementGuid>f40f64e6-4599-4ca2-902e-4857c22c0596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LLDuration</value>
      <webElementGuid>9c6fa42e-790a-4230-a644-1f8dff255f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>LLDuration</value>
      <webElementGuid>97b1f7a9-40ce-4dc0-899b-7d71e2a2a2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_LLDuration AVG_LLDuration</value>
      <webElementGuid>91c4b807-45d5-43fc-94dd-d44d27ccbc87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LLDuration&quot;)</value>
      <webElementGuid>2ef61a18-a7b1-4442-a4fa-6508e2d8cdc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LLDuration']</value>
      <webElementGuid>c9241bcf-0aa4-4c33-b460-6d56e8c76396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[6]</value>
      <webElementGuid>9465dcbb-708d-44b9-b1c9-feb40e2220b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/ul[6]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>4df7b860-28d1-4f64-a5f0-8815908dd813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'LLDuration']</value>
      <webElementGuid>3ab5c4b3-4fcc-4222-be86-41389d656be0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
