<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Swipe Transactions_User</name>
   <tag></tag>
   <elementGuidId>517ad175-8e70-4da9-9c56-47e8b0f10dd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Swipe_Transactions_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Swipe_Transactions_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Swipe_Transactions_id</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>522d8a7c-960a-4b13-80fc-83cb3048b39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>559ec741-7ad8-467e-b3a3-95363b80207c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Swipe_Transactions_id</value>
      <webElementGuid>74449e6a-9c06-4e2a-9140-a01b3b7d3947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>85c61ceb-47b2-498d-83cf-988390ff8e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>dfb4a56a-4a6e-4eb1-8b09-c006788d26ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SwipeTrans</value>
      <webElementGuid>ef73ce68-98d4-443d-86dd-1d5aa989bbe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk</value>
      <webElementGuid>992fc98e-347c-4365-aa64-45dd676486c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Swipe_Transactions_id&quot;)</value>
      <webElementGuid>14e26130-5fd2-4c59-9e38-11a0b3bd4ca3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Swipe_Transactions_id']</value>
      <webElementGuid>ed477e5f-15fb-46fd-a504-4d8a37ddb54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/span[5]/input)[9]</value>
      <webElementGuid>269d0ce6-1c1e-4bc9-b6c5-c23be0fb1463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li/ul[4]/li/div/span[5]/input</value>
      <webElementGuid>4f88291a-7251-463c-8905-d348e95f11eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'Swipe_Transactions_id' and @name = 'chk']</value>
      <webElementGuid>190e269b-b544-446e-a87d-de21f2bdd39c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
