<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ActivtyDashBoard</name>
   <tag></tag>
   <elementGuidId>e755db0d-cd25-4b4f-a6f8-22d926c72ff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ActivityDashBoard</name>
      <type>Main</type>
      <value>menuitem_1</value>
      <webElementGuid>70c89f95-efe9-42ef-a089-00be74c2471e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
