<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WorkTimeActivityDash</name>
   <tag></tag>
   <elementGuidId>b67e4566-04a1-4aa7-937b-6e8d0dae4697</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workTimeLiToggle2</value>
      <webElementGuid>74a867c0-3530-42d8-b821-b83bf374ea5b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
