<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Exp. Productive Hours_Main</name>
   <tag></tag>
   <elementGuidId>4197498e-16b0-4b21-994c-76b05d23503e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exp_productiveHrsid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exp_productiveHrsid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#exp_productiveHrsid</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6799b71-6138-4b20-aabf-9ba519f3751c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>57434633-7721-4ede-94bc-c471120980fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exp_productiveHrsid</value>
      <webElementGuid>31e11fbc-703f-40c2-9a78-a0a1ebb9c039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>0ffabb63-362c-4943-89d3-74630ffa7b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>a247f9fc-12c4-4c63-aa57-b6cb6e163ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Exp_ProductiveHrs</value>
      <webElementGuid>a25d4090-126e-4113-9b2f-6061541ecd2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk</value>
      <webElementGuid>15357d22-4fe2-43df-8cf2-38cc58bd835d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exp_productiveHrsid&quot;)</value>
      <webElementGuid>468c73ac-fd5b-48b9-9b57-7a2e5f13ff35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exp_productiveHrsid']</value>
      <webElementGuid>c755f96d-0ac6-4ad1-b33c-2d04bb849b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/span[4]/input)[9]</value>
      <webElementGuid>2411f364-bf6e-4376-baf3-24d69ea2cdd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul[4]/li/div/span[4]/input</value>
      <webElementGuid>a1390040-69c1-4873-ab1d-b4146035245a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'exp_productiveHrsid' and @name = 'chk']</value>
      <webElementGuid>12cf80d7-18ab-4a2a-b80d-9ef6fb48e73d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
