<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Exp. Logged Hours_Main</name>
   <tag></tag>
   <elementGuidId>afcbe7e4-416e-44c2-a1fa-c4c64fccddd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exp_loggedHrsid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exp_loggedHrsid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#exp_loggedHrsid</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9d0b65f-0e1b-4e43-8d22-c8d87c58c7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>61bf182b-d8b0-41c9-a4d8-a37dea6abf36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exp_loggedHrsid</value>
      <webElementGuid>3b940820-cb3b-46e8-8ec0-ed83bc1cd7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>ef2ee888-cf77-42ae-bfc7-3e02146d6bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>bc230c63-6d11-499c-b24f-ee89228ffa4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Exp_LoggedHrs</value>
      <webElementGuid>6344caf2-2a74-4d8e-9846-824565798c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk</value>
      <webElementGuid>a1388f76-417c-4bdb-b5d8-d7a5c3752e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exp_loggedHrsid&quot;)</value>
      <webElementGuid>3c0d097c-7a95-475c-9cfd-b40055a80f12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exp_loggedHrsid']</value>
      <webElementGuid>f7b41c22-37de-425d-9d0f-91e5a234db7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/span[4]/input)[11]</value>
      <webElementGuid>c57750f6-7e48-4b25-a565-d2c7448d343d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul[5]/li/div/span[4]/input</value>
      <webElementGuid>76b95168-447e-42fd-b2cd-6b8008b8148c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'exp_loggedHrsid' and @name = 'chk']</value>
      <webElementGuid>6e4596e7-3564-49ab-9c54-17d5f4ad8615</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
