<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Exp. Idle Hours_Main</name>
   <tag></tag>
   <elementGuidId>143de7d4-b9c2-455e-9f13-a4f44265fa27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exp_idleHrsid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exp_idleHrsid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#exp_idleHrsid</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9821ef05-0bbe-435e-89fc-252a3a0ba59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>def3d66f-38c7-4874-83c9-31864cea7a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exp_idleHrsid</value>
      <webElementGuid>99c053dd-a153-4b97-89ec-dd5970693efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>e0183a51-d906-4662-94ca-77ea127a0275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>d7374c95-2f75-494e-b64e-1d1b354674d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Exp_idleHrs</value>
      <webElementGuid>eb1ab003-cc86-47e8-bdd5-9cb77d1e3142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk</value>
      <webElementGuid>c0c0c1db-5ea1-468d-84f8-549bfdfc300f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exp_idleHrsid&quot;)</value>
      <webElementGuid>b8dee99e-32d0-474c-95fc-4db1f39d15e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exp_idleHrsid']</value>
      <webElementGuid>9b12b05a-2208-4d44-a5d1-b6c40fb744e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/span[4]/input)[17]</value>
      <webElementGuid>e7a82f3e-0317-45f2-b0cb-4345e4c39303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul[8]/li/div/span[4]/input</value>
      <webElementGuid>5224e8b2-5a8f-4a72-bfe1-bc01b873c63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'exp_idleHrsid' and @name = 'chk']</value>
      <webElementGuid>d707ca77-f4b8-470e-a467-4515851328ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
