<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Report Duration</name>
   <tag></tag>
   <elementGuidId>782bbc3b-58a3-4bbe-b9d7-fb4d87fc55ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#showByGroup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='ReportFilterDurationFormBean']//input[@id='reportDuration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Display data&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6d2562d-19c0-4932-a307-4b40c9338e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8375f842-51f4-4157-a4fd-7d8d131739d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>showByGroup</value>
      <webElementGuid>ca7d6bbc-41ce-45fc-9e91-20684866e945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>showByGroup</value>
      <webElementGuid>556e498f-fe93-4e2f-b19f-4f8392b4495e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>df4fcdcb-4d0a-453d-a6af-ede748b7f1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnCheckShowByGrpOnClick</value>
      <webElementGuid>ef9ff8b4-0e00-439e-9a78-a994eed1c5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showByGroup&quot;)</value>
      <webElementGuid>c0547806-84d7-4575-9b07-7f570540ac07</webElementGuid>
   </webElementProperties>
</WebElementEntity>
