<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EnableFilterCH_Chk</name>
   <tag></tag>
   <elementGuidId>5516dda0-b021-488f-acc6-e6d949d321f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lhChkBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lhChkBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ignoreLoggedHours >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>99f36756-e667-42a2-9b88-f46f33e8290a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>404a1578-a708-4dd3-b0b0-1957d6e7b04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lhChkBox</value>
      <webElementGuid>121ac058-c2ef-4c38-87de-c77ec5eb9c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnEnableLHTypeOnClick</value>
      <webElementGuid>91fb53ff-1be6-4f1b-a10d-268aa7ef7095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param1</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>04bbdfeb-08fd-497f-8f7a-459c2e9c4b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lhChkBox&quot;)</value>
      <webElementGuid>391440dd-e8d2-4949-8ba1-ba9627d328f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lhChkBox']</value>
      <webElementGuid>4e5284c9-4aa3-4d49-8b43-cf1261051658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ignoreLoggedHours']/span/input</value>
      <webElementGuid>a362760e-a45a-4e7a-ae7f-357f63c860ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span/span/input</value>
      <webElementGuid>ec2ef5c6-d85f-40a3-bb84-8c8bbe81549e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'lhChkBox']</value>
      <webElementGuid>29da4fe6-98c2-4795-8a1e-2190795e8668</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
