<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EnableFCDays_Chk</name>
   <tag></tag>
   <elementGuidId>3e84dd5a-f0ca-4bea-8c96-8d11c57e9139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='manDaysTypeChkBox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#manDaysTypeChkBox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#manDaysTypeChkBox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f0bb311-4b19-47d1-b4a5-3b4802d5215b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>08f1b3e3-a46a-42c8-83e0-04a9f90a0f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>manDaysTypeChkBox</value>
      <webElementGuid>2d997bca-85f2-46a0-bb64-8faa8eee81bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnEnableManDaysOnClick</value>
      <webElementGuid>ffe83eb7-3e6e-4b45-9a04-9f4f1d2e3530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param1</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a545e245-17eb-4083-b20e-6d3d8714d5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manDaysTypeChkBox&quot;)</value>
      <webElementGuid>f3b58ea2-fa51-4689-95cf-34a52c65d409</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='manDaysTypeChkBox']</value>
      <webElementGuid>f30c9a0c-d897-4331-aa56-060ca619c743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ignoreManDays']/span/input</value>
      <webElementGuid>e353c35d-4a45-4878-bc9a-8d1a71e3b9b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span/input</value>
      <webElementGuid>203cb1bb-2903-4cc3-9d1c-7d983d8416a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'manDaysTypeChkBox']</value>
      <webElementGuid>f67c362a-567e-4ba0-bde1-22aa365d9439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
