<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FilterTypeCD1_Select</name>
   <tag></tag>
   <elementGuidId>b7f64cef-b412-47a0-a778-6bb0da60c735</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='manDaysType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#manDaysType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#manDaysType</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>48651260-c549-4b93-914c-ccdea5ece849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>manDaysType</value>
      <webElementGuid>7ada5336-aa00-4120-b937-ca6900e11fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onchange</name>
      <type>Main</type>
      <value>fnManDaysTypeChangeOnChange</value>
      <webElementGuid>3ee1bac7-c0f3-425b-9e82-a19ade769315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>manDaysType</value>
      <webElementGuid>6b17e2ab-cb2c-4639-8731-8486c418dfd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-filter width-80px</value>
      <webElementGuid>6bd7e86d-5363-4434-a243-816aea3fdaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					Ignore
					Consider
			  	</value>
      <webElementGuid>2200a802-3925-4a1f-be15-1b38fcc4b24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manDaysType&quot;)</value>
      <webElementGuid>72321ce4-d225-44e3-8087-e769b3dfcda3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='manDaysType']</value>
      <webElementGuid>ab5776cb-9283-4bd0-a878-e07faf606924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ignoreManDays']/span[2]/select</value>
      <webElementGuid>06b77651-c99b-43ec-b2e0-9afea9ec0d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[AND]'])[1]/following::select[1]</value>
      <webElementGuid>b5d79b7e-8c38-4386-a293-ee39185607ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='days'])[1]/preceding::select[2]</value>
      <webElementGuid>8767fc6a-c893-444d-9c96-9b574510520c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span[2]/select</value>
      <webElementGuid>4ce055d4-3961-4140-a456-fef5f8cdf3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'manDaysType' and @name = 'manDaysType' and (text() = '
					Ignore
					Consider
			  	' or . = '
					Ignore
					Consider
			  	')]</value>
      <webElementGuid>9b72370f-f014-4538-8392-3e5ff6fad7c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
