<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FilterTypeHours_Select</name>
   <tag></tag>
   <elementGuidId>5fd2f8f4-a5cc-462f-8752-69b340a06514</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='lhType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lhType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#lhType</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f0ab5b53-4d68-46b9-a050-8dc16ef5b4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lhType</value>
      <webElementGuid>0da9821e-908c-4e9e-864e-346a3b7844be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onchange</name>
      <type>Main</type>
      <value>fnLHTypeChangeOnChange</value>
      <webElementGuid>dd98fb5e-0e59-4ee7-87a7-968607204abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lhType</value>
      <webElementGuid>e4bd38a2-1aec-47b9-a845-7db0efbaac7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-filter width-80px</value>
      <webElementGuid>09ea8eb8-db3f-4c76-b352-1334a067aff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					Ignore
					Consider
			  	</value>
      <webElementGuid>42280cdb-1b3b-4216-a755-d752a9142b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lhType&quot;)</value>
      <webElementGuid>54af7c8c-402f-4bbf-aa5e-1194c6750572</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='lhType']</value>
      <webElementGuid>b1337825-c667-4818-a4c1-13268d0719f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ignoreLoggedHours']/span[2]/select</value>
      <webElementGuid>676ff64b-d020-43bc-9ce3-d1c0fc856ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work Day [+2]'])[1]/following::select[1]</value>
      <webElementGuid>ead2e0ed-659e-441f-9aa0-a5658edec3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='min'])[1]/preceding::select[2]</value>
      <webElementGuid>5c401818-37c6-43bf-909d-4ca1c0001817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]/select</value>
      <webElementGuid>b5ed7f53-f563-4ad3-abbe-3fa6f58a7542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'lhType' and @name = 'lhType' and (text() = '
					Ignore
					Consider
			  	' or . = '
					Ignore
					Consider
			  	')]</value>
      <webElementGuid>136e1a91-6da2-41cc-91ff-83b737c95876</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
