<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Person DaysTo_Text</name>
   <tag></tag>
   <elementGuidId>13e7c94f-7b53-4cfb-a74e-df6386a76ba7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='manDaysTypeValue2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#manDaysTypeValue2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#manDaysTypeValue2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>526c39c8-aa4e-4425-8d8c-222cdb9291cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b11fb422-7f37-47fc-9a2b-db239a6589a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-filter width-60px-padding-5px-text-align-right</value>
      <webElementGuid>3da497b5-c9d5-4586-bf49-221d23c88e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>manDaysTypeValue2</value>
      <webElementGuid>bbf9cda6-3d0c-42aa-8f07-8c37c48dbbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>642a986c-bad0-494c-9759-6b1a3e7bb4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>manDaysTypeValue2</value>
      <webElementGuid>c2533914-908a-4068-abfd-fc4a7204d64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manDaysTypeValue2&quot;)</value>
      <webElementGuid>c8da9d24-f127-4805-a175-2d4ea1a7592a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='manDaysTypeValue2']</value>
      <webElementGuid>479a5714-5c75-4c15-8ad5-26ff177c4bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='manDaysTypeValue2Div']/input</value>
      <webElementGuid>d12748ca-b6e9-4186-ae3e-09f8462188b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span[5]/input</value>
      <webElementGuid>abd9e2b3-3197-41f6-9e2b-60569e0f7e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'manDaysTypeValue2' and @name = 'manDaysTypeValue2']</value>
      <webElementGuid>33a64d50-414b-4536-a0e7-96890f150717</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
