<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Person DaysFrom_Text</name>
   <tag></tag>
   <elementGuidId>a36af704-73fe-4eea-a853-9ab91b0a766c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='manDaysTypeValue1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#manDaysTypeValue1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#manDaysTypeValue1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2bf9dbe1-5bd8-44c6-bf23-7e41054e2838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>35a7d55a-7b4b-4887-9457-1455a3428cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-filter width-60px-padding-5px-text-align-right</value>
      <webElementGuid>410cab34-7958-4ebc-adc6-d8783d1e7582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>manDaysTypeValue1</value>
      <webElementGuid>636c64bc-6c4b-4d47-88f7-b26a8c8a90f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>manDaysTypeValue1</value>
      <webElementGuid>7934bcdc-5f79-460d-9bb8-96c722860fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f30a422b-5de1-41a6-b186-d5b7a7d5e9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manDaysTypeValue1&quot;)</value>
      <webElementGuid>4ad123a2-2a4f-494c-bf24-d4b11211fa56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='manDaysTypeValue1']</value>
      <webElementGuid>f77d5c3f-5a69-4e4b-9569-f769b59ad9e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='manDaysTypeValue1Div']/input</value>
      <webElementGuid>d811adb4-51b9-4689-aa9d-d9253fbe8e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span[4]/input</value>
      <webElementGuid>664efb75-4b5a-489b-aff2-8a264fb15d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'manDaysTypeValue1' and @name = 'manDaysTypeValue1']</value>
      <webElementGuid>bed54129-6001-409a-bb4a-4cc3e430a8b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
