<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Neutral (TAFS)_Main</name>
   <tag></tag>
   <elementGuidId>7d1e7d04-2321-43bc-8f0e-510b19ee8662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TAFS_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TAFS_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TAFS_2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d0d68e1-e12e-4fd0-805d-53be9d162ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bb6cf8c6-397a-42de-b2fb-9f601852b528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>f1b23283-e466-45d9-9cb8-636b7b5b846b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TAFS_2</value>
      <webElementGuid>f64c075a-079a-4aa1-a2b0-6081a29ebe93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TAFS_2</value>
      <webElementGuid>ec1423ec-e495-4d3a-b8ad-0e04a2f6c96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>TAFS_2</value>
      <webElementGuid>6fa37e6d-2278-4959-9387-4fa936a32563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_TAFS_2 AVG_TAFS_2</value>
      <webElementGuid>1c038629-3e8e-4b72-ada2-4243155faf3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TAFS_2&quot;)</value>
      <webElementGuid>79b17ef8-7c56-4d4c-966a-e5f212c94322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TAFS_2']</value>
      <webElementGuid>e8316757-5ea4-4234-bb1b-5fe84acd354a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[46]</value>
      <webElementGuid>302e7e27-ef39-4e2d-b25d-e4c8d62dd819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul[2]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>7ed47c1f-59d2-44ca-acda-82a0b4bc1ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'TAFS_2']</value>
      <webElementGuid>7048e1c4-6bbc-4295-bfef-68abb7c3bec7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
