<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Not Rated (TAFS)_Avg</name>
   <tag></tag>
   <elementGuidId>26575958-0166-449e-adc4-e0a3fa1b0dd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AVG_TAFS_N_R</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AVG_TAFS_N_R']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AVG_TAFS_N_R</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71a6e76d-eb85-465e-8df9-b31d3f4d0fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>02b68a61-c509-4c68-ba48-3f752dfbb122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>5b59470f-b887-4eeb-be34-bb4792a4fc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AVG_TAFS_N_R</value>
      <webElementGuid>642ecdf2-645d-4e8b-9d44-53b71fc92e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>f547a10b-7f5c-49d7-8b37-806200f53b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AVG_TAFS_N_R</value>
      <webElementGuid>5a0f07f8-52ea-47de-9dda-4988062c6251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-classname</name>
      <type>Main</type>
      <value>TAFS_N_R</value>
      <webElementGuid>9f130bc3-97c4-4912-b0f0-1114e0393939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk TAFS_N_R vertical-align-top</value>
      <webElementGuid>c8577dd5-4ac0-49ad-91a6-ce83819545b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AVG_TAFS_N_R&quot;)</value>
      <webElementGuid>49f80034-d55d-4ed8-94ba-eccd48d05b73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AVG_TAFS_N_R']</value>
      <webElementGuid>180d629b-3798-4d8d-a7f0-bf4e254e6e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr[3]/td/span/input[3])[12]</value>
      <webElementGuid>c5f7977a-1b54-493c-b6bf-0c1759963f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul[4]/li/div/table/tbody/tr[3]/td/span/input[3]</value>
      <webElementGuid>e1e18323-48c9-4a4e-b353-cb8ecb202dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chk' and @id = 'AVG_TAFS_N_R']</value>
      <webElementGuid>1aa92341-be06-4076-943c-4e8500b1be0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
