<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Not Rated (TAFS)_Main</name>
   <tag></tag>
   <elementGuidId>740e1852-e165-49eb-b6eb-90c9ed666b43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TAFS_N_R</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TAFS_N_R']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TAFS_N_R</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc600bda-de3f-40c8-bcde-5f62eceef15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4ee2c92a-2aed-4061-a6d4-538a39cd7b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>941efdf3-4a1d-43c7-af2f-c7632aa47fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TAFS_N_R</value>
      <webElementGuid>ebeed38b-bcd3-481c-aa16-5f2b3915b98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TAFS_N_R</value>
      <webElementGuid>6c62a20e-45bd-484f-938e-3a3884b912e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>TAFS_N_R</value>
      <webElementGuid>3dbb7665-a564-44bf-a481-4ea0a43094ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_TAFS_N_R AVG_TAFS_N_R</value>
      <webElementGuid>c5d6e878-cef2-4991-a5d2-38044cda9fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TAFS_N_R&quot;)</value>
      <webElementGuid>2e33eb8d-bfb9-44de-ba9f-0bc8658b1ae4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TAFS_N_R']</value>
      <webElementGuid>0a6722a9-e81a-4c25-952e-ed3efaad39c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[56]</value>
      <webElementGuid>79aff254-ef21-4560-99c8-49a44c356ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul[4]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>3c3b62bc-facf-4c57-9473-ccd85806ad6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'TAFS_N_R']</value>
      <webElementGuid>4f9bd244-39a0-41c4-bb74-efba0c8aae86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
