<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Productive (TAFS)_Main</name>
   <tag></tag>
   <elementGuidId>79844ae8-230a-4c60-a85c-5b0b01929aef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TAFS_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TAFS_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TAFS_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>151aab16-1013-423c-8256-98c3a9ee920a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0d34507a-45b2-40c4-ad19-2a58b6666327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>418e728b-d0db-48bc-b9f9-55c4fd7eec70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TAFS_1</value>
      <webElementGuid>7acbba7c-ef30-44fd-8a16-ccc7b253a45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TAFS_1</value>
      <webElementGuid>18ddb6fa-af41-49c3-bb87-0404343fbf86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>TAFS_1</value>
      <webElementGuid>f30b0e25-fb35-4749-9a80-26e04a9be8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_TAFS_1 AVG_TAFS_1</value>
      <webElementGuid>9cddd29a-3844-4041-9b11-f036ec5200b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TAFS_1&quot;)</value>
      <webElementGuid>ed7c494d-b844-48ff-9976-e82ffa85edb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TAFS_1']</value>
      <webElementGuid>1792f028-91c0-49e4-946a-f64104c75830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[41]</value>
      <webElementGuid>f015fa3c-f377-424a-b501-c916a8f2b39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/ul/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>ea5d824a-e1e3-407c-ab7c-750774855bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'TAFS_1']</value>
      <webElementGuid>5a35f3f9-01be-461f-8428-4af8060215fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
