<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unknown (TAFS)_Avg</name>
   <tag></tag>
   <elementGuidId>a3735e48-e933-4eb1-9d04-cf4ad8497056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Tafs_UApp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AVG_Tafs_UApp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Tafs_UApp</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbfe91f3-34d7-459b-bad4-2e9390b7e304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0e699c9c-03f9-45a3-8300-edc0f17b9276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>5a02fecf-4c62-4537-86e7-b1bf5ca63f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Tafs_UApp</value>
      <webElementGuid>289219b7-ac31-4e65-a3ee-10afeee81482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tafs_UApp</value>
      <webElementGuid>81948271-9c99-4ba8-8c27-cee3c3f6fcf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>Tafs_UApp</value>
      <webElementGuid>8e54429d-cde6-48f2-932c-dfa346b0185c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_Tafs_UApp AVG_Tafs_UApp</value>
      <webElementGuid>35a0adc0-f48b-44dd-ae8b-45c5c25b8115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Tafs_UApp&quot;)</value>
      <webElementGuid>0bf128c6-6d0b-43ae-bb10-453bb66ea364</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Tafs_UApp']</value>
      <webElementGuid>594124fb-e838-4839-895b-0f2b19c62fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[61]</value>
      <webElementGuid>762bf2da-32d5-4f80-8787-2bc748aee3a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul[5]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>2a6022ef-3ef2-4ac9-b094-82d67e52609a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'Tafs_UApp']</value>
      <webElementGuid>45eff0f6-20b1-46d2-b19f-a7f20b0b2003</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
