<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>weeklyOff_Chk</name>
   <tag></tag>
   <elementGuidId>36b62fd9-ed2c-4442-84f6-d9e6d0d6f5c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='WO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=checkbox[name=&quot;Weekly Off &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>987a9341-daaf-4270-ace3-c1988fe171a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>11e25070-76d1-48b4-ad46-236a45ecc0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>actionSel modal_dayType</value>
      <webElementGuid>d6d92609-5565-4935-888d-f1502ea6d526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WO</value>
      <webElementGuid>99e1b01a-6ee2-40ba-bb31-ba66538dd20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>WO</value>
      <webElementGuid>b8139331-f404-4047-aa4f-066425857ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnCheckSelectAllDayTypeOnClick</value>
      <webElementGuid>ab0fc2c1-0ba1-47cf-87ba-1f2a97e8cfb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param1</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a117cbe7-4d37-4684-8841-8a6de109eb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-param2</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>84eaca41-3574-46e9-9b5a-55271c4fd343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WO&quot;)</value>
      <webElementGuid>86eec5da-4361-4361-a2a0-7fa821a643b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='WO']</value>
      <webElementGuid>12912921-c69b-4d7c-9fe0-605d54ab50ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dayTypeTable']/tbody/tr/td/table/tbody/tr[4]/td/div/input</value>
      <webElementGuid>d450a381-bb96-44e0-b528-806d741effb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div/input</value>
      <webElementGuid>2442ea3d-baf9-4220-9cb1-6033961424f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'WO']</value>
      <webElementGuid>d67be850-d260-48af-b75f-9d81d4601bfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
