<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Non Productive Hours_Main</name>
   <tag></tag>
   <elementGuidId>978f40eb-7d60-4c0f-96ef-bbd079d5ae6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TH_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TH_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=cell[name=&quot;Non Productive Hours&quot;s] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13622dc0-834e-418d-9367-61fbb4bdbbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6ecba103-febd-4aa0-9207-7e701182959b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>c6896cf6-39d6-4b61-9009-5603b0ae6b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TH_3</value>
      <webElementGuid>98424b47-2145-48a6-ab71-1c2d57b4bce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TH_3</value>
      <webElementGuid>0f864488-2d98-4d64-a912-71183bf6faa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>TH_3</value>
      <webElementGuid>4d424806-daa1-4a8b-86a7-e8510a4302b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_TH_3 AVG_TH_3</value>
      <webElementGuid>758aad58-8d35-4f6f-aa99-09c0fc3598bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TH_3&quot;)</value>
      <webElementGuid>1f097857-038b-4225-8c19-81bc054ad9db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TH_3']</value>
      <webElementGuid>fedf27ef-7049-460a-acad-0b07466acc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[36]</value>
      <webElementGuid>27dd4355-792b-4365-92c0-869856233d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul[3]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>77aed369-4a0e-4771-b1d6-be34f698fb67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'TH_3']</value>
      <webElementGuid>07e31816-3c7f-469a-bd5e-9dfbc8af95df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
