<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Not Rated Hours_Main</name>
   <tag></tag>
   <elementGuidId>963c2a6b-2d3e-439e-9440-280a0ef946f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TH_N_R</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TH_N_R']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TH_N_R</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>271724f8-74ad-4d5a-925d-3a454f6a021b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5e46e79f-9992-44f4-a9a6-b075695033ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>e594f7c6-73c5-423f-99b7-61622013a3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TH_N_R</value>
      <webElementGuid>5bbfb34c-6449-4c9a-a877-1449dff15565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TH_N_R</value>
      <webElementGuid>22d8f375-f11d-4ef7-803e-20c7b739ec69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>TH_N_R</value>
      <webElementGuid>c52520e7-b0d4-470f-a3e7-0d7b856ba3e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_TH_N_R AVG_TH_N_R</value>
      <webElementGuid>f523d3cd-e01a-4fa6-9c7c-dcca2d3e48a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TH_N_R&quot;)</value>
      <webElementGuid>6e2ef2cd-ec02-4c4b-ada8-04656086e048</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TH_N_R']</value>
      <webElementGuid>4b06fc2d-6552-4505-8065-8ad8dcd20d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[41]</value>
      <webElementGuid>81692629-a848-43c2-af7a-5b27694c516b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul[4]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>052e17c3-6b75-48ab-bace-d5a78c8a1098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'TH_N_R']</value>
      <webElementGuid>85a49355-c781-4fe8-9672-470a32b3084f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
