<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Personal Time Hours_Avg</name>
   <tag></tag>
   <elementGuidId>0afaaad0-5280-42ab-9015-a1747ac63363</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AVG_Total_Personal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AVG_Total_Personal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AVG_Total_Personal</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b78865e0-bebf-42d6-9216-117fdda86b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0c8e998a-9b31-424f-9cbb-307fd4196f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>5d9b7bbe-9498-41b9-87b1-937200815827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AVG_Total_Personal</value>
      <webElementGuid>f2108db5-a0b5-4cc8-9a59-4ccc8cc08de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>8dadf5b2-1ed6-4bfb-ab83-0501695e01d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AVG_Total_Personal</value>
      <webElementGuid>cb2ae0de-4ecb-48ed-b131-b683c3de6a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-classname</name>
      <type>Main</type>
      <value>Total_Personal</value>
      <webElementGuid>8394197f-ce82-49d9-a8dd-f07f4997ba29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk Total_Personal vertical-align-top</value>
      <webElementGuid>b0d430fc-bf9e-4aa0-b82e-dddaae097f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AVG_Total_Personal&quot;)</value>
      <webElementGuid>bc5f265b-56be-4a33-a2af-1ef7daf0d438</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AVG_Total_Personal']</value>
      <webElementGuid>3f551565-1849-433d-a1a9-3c27ba2a7543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr[3]/td/span/input[3])[11]</value>
      <webElementGuid>1355e64e-338c-4b96-8533-ece2ce3b66aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul[6]/li/div/table/tbody/tr[3]/td/span/input[3]</value>
      <webElementGuid>dd2032d6-4d72-4c9f-828c-2e01cf3618d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chk' and @id = 'AVG_Total_Personal']</value>
      <webElementGuid>38265ec6-ded4-4ff4-bcdd-337010c4c0f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
