<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Personal Time Hours_Main</name>
   <tag></tag>
   <elementGuidId>c1925fbd-3087-4224-b9e1-92413c50b64b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Total_Personal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Total_Personal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Total_Personal</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7ebdea2-b690-486e-8781-36333d89cca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>813f48ac-2c01-4e7b-a034-1c2adf665003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>6e765cd9-a49d-49ce-bd3f-77a6cc4a5e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Total_Personal</value>
      <webElementGuid>76a6c678-a146-4e86-87e1-a0d80af628a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Total_Personal</value>
      <webElementGuid>9ec8bf50-1f42-453f-9d1f-ef0f2bd2301e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>Total_Personal</value>
      <webElementGuid>f4de9762-5756-4993-8dd5-46349fbac39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_Total_Personal AVG_Total_Personal</value>
      <webElementGuid>be1845f5-8200-4b40-8644-863574d6957f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Total_Personal&quot;)</value>
      <webElementGuid>ffdd849a-e7c6-4c57-a093-fd0b8d8809a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Total_Personal']</value>
      <webElementGuid>44cc8452-c458-4645-a021-92c9cef8466e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[51]</value>
      <webElementGuid>9c206f25-e454-4411-bf1a-5d83c7d0dbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul[6]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>32aa19cd-3808-462a-8707-8d6190b2c0f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'Total_Personal']</value>
      <webElementGuid>88ce894f-c0c4-41ca-b52a-2240d4b583e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
