<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Productive Hours_Tot</name>
   <tag></tag>
   <elementGuidId>1a075c6d-cc56-4afc-9a5d-10a5a718a3f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TOT_TH_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TOT_TH_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TOT_TH_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ea15a4b-b7a1-4eae-8c15-92034a5897ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>68824ee5-95af-499c-9381-de813d7016cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>614618dc-b4c0-4191-81ab-a7e117ad1ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TOT_TH_1</value>
      <webElementGuid>3188294d-6315-4b86-b984-f9d8aff0a4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>7ceac316-4488-43dc-9191-26274f2129f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TOT_TH_1</value>
      <webElementGuid>50d0df7e-91ce-40e1-820e-ce21c8400950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-classname</name>
      <type>Main</type>
      <value>TH_1</value>
      <webElementGuid>cec0612e-165d-4406-a11f-a80eb520ab8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk TH_1 vertical-align-top</value>
      <webElementGuid>19b68c6f-1083-40c4-bb35-0d5417118cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TOT_TH_1&quot;)</value>
      <webElementGuid>9fb60b0c-7f31-442a-96a0-10515d3cd41b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TOT_TH_1']</value>
      <webElementGuid>79d354d5-9d6d-4be1-a66f-9efd96f1da4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr[3]/td/span/input)[9]</value>
      <webElementGuid>bdeb1392-fec3-4b00-8997-333dc2adba7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[3]/ul/li/div/table/tbody/tr[3]/td/span/input</value>
      <webElementGuid>574eb124-d7f8-41ef-9cee-c510c42c78a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chk' and @id = 'TOT_TH_1']</value>
      <webElementGuid>67250d1d-943a-4caf-b40b-61ce64f16d68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
