<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Productive Hours_Main</name>
   <tag></tag>
   <elementGuidId>0dc9f174-b8b8-45c6-baa0-9b534f9761f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TH_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TH_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;Productive Hours&quot;s] >> internal:role=checkbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fad98e3-e676-41c5-96b5-4a6e9c785783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1490dfc7-6d37-4d1b-b540-5c9a0c3ebaed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>282394c5-fbdf-47e7-8c3a-0a3f06db20b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TH_1</value>
      <webElementGuid>f3d3e4d9-d46b-4bd3-85fa-ff1a3534d5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TH_1</value>
      <webElementGuid>92c9f06f-aa62-4e7a-9182-dc424ac42c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>TH_1</value>
      <webElementGuid>8a241794-c691-4174-ab21-8339a46e8f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_TH_1 AVG_TH_1</value>
      <webElementGuid>344cb9b7-68be-4253-a3b0-e36e716e11c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TH_1&quot;)</value>
      <webElementGuid>51c3e7d7-e72c-4aa8-a427-c022e885ebf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TH_1']</value>
      <webElementGuid>318640d9-d2fe-4102-b97b-328ac4306b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[11]</value>
      <webElementGuid>4b367a75-ed98-46ec-b2ae-8d72bd204690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[3]/ul/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>b9ac5122-072f-4ab3-bd7f-bd5f2b4aec09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'TH_1']</value>
      <webElementGuid>b9ce85ae-92a2-4902-a01e-51c7dadd7ffc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
