<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Productive Hours_Avg</name>
   <tag></tag>
   <elementGuidId>f3319604-ebb1-489c-b0d6-4529321f3c9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AVG_TH_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AVG_TH_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AVG_TH_1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>217061e4-1492-4eec-af7c-edf03983638b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a4939343-3eb7-463b-99e8-69e06087945a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>5dc7c7fe-7d02-4399-9de2-0827c2f71e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AVG_TH_1</value>
      <webElementGuid>11bbeb2f-6c37-436c-ab98-94bb0a723dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>330bee63-c756-45bf-9874-73467ac2ca28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AVG_TH_1</value>
      <webElementGuid>cfdd1ee2-ea00-4032-af7f-24d0a33b944e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-classname</name>
      <type>Main</type>
      <value>TH_1</value>
      <webElementGuid>25d9826f-2223-4e22-ae32-78a7afcd157e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk TH_1 vertical-align-top</value>
      <webElementGuid>813a97a7-e253-4f72-ae1c-00e0773c248e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AVG_TH_1&quot;)</value>
      <webElementGuid>df1522de-67b7-40eb-9ad3-cc83528d2ab5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AVG_TH_1']</value>
      <webElementGuid>fd5e3b33-a89a-4233-a13d-a67412430961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr[3]/td/span/input[3])[3]</value>
      <webElementGuid>421a5601-a771-4e4c-9f62-ffe173155196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[3]/ul/li/div/table/tbody/tr[3]/td/span/input[3]</value>
      <webElementGuid>a6651dcd-e381-4512-aa6e-8ea37c4df241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chk' and @id = 'AVG_TH_1']</value>
      <webElementGuid>7cb70ef4-1f90-4f37-b6d0-5a4587a7ec4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
