<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unknown Hours_Main</name>
   <tag></tag>
   <elementGuidId>52bcb129-0667-4c9d-8faa-b0c14e6dcab7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Total_UApp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Total_UApp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#Total_UApp</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>816638ab-6ee4-40b0-b881-e17fe8e60187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9da9070d-ccb0-44fb-a2b7-0e2718941d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnShowAdditionalRowOnClick</value>
      <webElementGuid>ceb69ff8-af01-4941-a0b7-e63eb700eaa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Total_UApp</value>
      <webElementGuid>7a6b81ab-e89b-4209-9992-ead6b3891a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Total_UApp</value>
      <webElementGuid>98a1ce49-86da-4206-bc64-2e0faca2a62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idname</name>
      <type>Main</type>
      <value>Total_UApp</value>
      <webElementGuid>2573abf4-8506-417a-882e-0110e84f69eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOT_Total_UApp AVG_Total_UApp</value>
      <webElementGuid>184b4be4-8a54-4a13-aa01-a06f45a2c434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Total_UApp&quot;)</value>
      <webElementGuid>d582d431-964f-41f8-af10-65d9b2f3f936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Total_UApp']</value>
      <webElementGuid>c5666cad-d12d-4188-919b-193e814b521b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr/td/span/input)[46]</value>
      <webElementGuid>e3b4cf8c-650d-47fc-b45d-62637c6d2119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul[5]/li/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>fc3e808f-80c9-4757-9ee4-64881748990c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'Total_UApp']</value>
      <webElementGuid>97c87567-973a-416c-80df-eb2540ea400a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
