<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unknown Hours_Avg</name>
   <tag></tag>
   <elementGuidId>172c8bb1-f0d9-4e62-8236-f43670d70be7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AVG_Total_UApp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AVG_Total_UApp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#AVG_Total_UApp</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6849558b-2bbd-4734-a0c3-563b2cbca39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>daa17347-03c2-43a3-b083-ce76146de434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>b73dcb4b-3f24-421f-9547-4bd207c4b5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AVG_Total_UApp</value>
      <webElementGuid>2ca1e95e-6ba5-48b2-9479-772fd5fc86f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-onclick</name>
      <type>Main</type>
      <value>fnAddElementOnClick</value>
      <webElementGuid>030fe6d2-8537-47e0-887b-015fea376cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AVG_Total_UApp</value>
      <webElementGuid>d848a5e6-c1ac-46e7-bf72-a7c32a6cf895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-classname</name>
      <type>Main</type>
      <value>Total_UApp</value>
      <webElementGuid>0e801523-dbd4-4a5e-b59c-a8cb76cdea34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>efficiencychk Total_UApp vertical-align-top</value>
      <webElementGuid>12b3336b-db24-49e3-b9be-0eacbccac3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AVG_Total_UApp&quot;)</value>
      <webElementGuid>14684c96-a586-4902-acab-f5f63f5eb92b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AVG_Total_UApp']</value>
      <webElementGuid>cbc26835-433c-4269-b838-c446b3a1706d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='current']/table/tbody/tr[3]/td/span/input[3])[10]</value>
      <webElementGuid>deea1913-a2cb-448c-8251-87045a6524b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul[5]/li/div/table/tbody/tr[3]/td/span/input[3]</value>
      <webElementGuid>8707dcb7-1588-4a3a-84b0-1444f1442ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'chk' and @id = 'AVG_Total_UApp']</value>
      <webElementGuid>0aba7cbd-05a8-451d-86da-e6b8a144bb4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
